### ISSUE TITLE
Forbidden on  https://dl.bintray.com/openhab/apt-repo2/pool/main/3.0.2/ when updating OH3 (on openHAB3 Branch) in openhabian-config

### ISSUE THREAD

**Issue by marcelser** [openhab/openhabian#1502] opened 2021-05-03 09:38 UTC
I know that Ubuntu on Odroid XU4 is not supported but I think downloading packages from openhab repo is not hardware dependent especially as it used to work flawlessly with OH2 & OH3 previously, right? cause when I run openhabian-config tool and I try "02 Upgrade System" I get the following Forbidden message on openhab repo from apt:

```
Err:1 https://dl.bintray.com/openhab/apt-repo2 stable/main armhf openhab all 3.0.2-1
  403  Forbidden [IP: 3.125.168.216 443]
Err:2 https://dl.bintray.com/openhab/apt-repo2 stable/main armhf openhab-addons all 3.0.2-1
  403  Forbidden [IP: 3.125.168.216 443]
E: Failed to fetch https://dl.bintray.com/openhab/apt-repo2/pool/main/3.0.2/openhab_3.0.2-1_all.deb  403  Forbidden [IP: 3.125.168.216 443]
E: Failed to fetch https://dl.bintray.com/openhab/apt-repo2/pool/main/3.0.2/openhab-addons_3.0.2-1_all.deb  403  Forbidden [IP: 3.125.168.216 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

```
I also tried with curl on the XU4 and nother x86 linux machine to fetch and I also tried downloading on my Windows machine using chrome browser the link:
https://dl.bintray.com/openhab/apt-repo2/pool/main/3.0.2/openhab_3.0.2-1_all.deb

No matter what I tried, I ended up with a 403 Forbidden.

I'm currently on OH3 3.0.1 on OpenHAB3 branch and tried to update to 3.0.2 and previously on OH2 and also OH3 3.0.0 and 3.0.1 updating always worked fine. So what's going on with that repo? Is there a change I need to be aware of or is the repo down? 

## System information:
OS: Ubuntu 18.04.5 LTS
HW: Odroid XU3
Please tell us what OS you are running (Raspberry Pi OS, Debian, Ubuntu), what
HW you are running on (Raspberry Pi, amd64). Also include the output of
`cat /etc/os-release` and `uname -m`.
```
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

```

```
armv71
```

**Comment by Diapolo** [comment] 2021-05-03 11:44
I can confirm that observation/error on my Raspi4 with latest OpenHABian!

**Comment by marcelser** [comment] 2021-05-03 14:29
don't know if it helps but I updated to the latest openhabian-config tool before running "02 Upgrade System" in the tool. So the tool is up to date

**Comment by marcelser** [comment] 2021-05-03 14:47
just checked my /etc/apt/sources.list.d/ repo files. I do have those 2 files:
`openhab.list` and `openhab2.list.save`, both pointing to `deb https://dl.bintray.com/openhab/apt-repo2 stable main`. I know that the `openhab2.list.save` will be ignored but still the openhab.list contains the bintray link.

I can change it manually if of course if I would know the correct repo link but still a good question why it isn't migrated automatically.

**Comment by mstormi** [comment] 2021-05-03 16:28
> but still a good question why it isn't migrated automatically.

No it isn't. The answer obviously is "because for things to work automatically someone has to program the automation".

If you select to upgrade/install OH from the 4X menus it'll overwrite the repo but no sooner.

**Comment by mstormi** [comment] 2021-05-04 13:29
Fixed by #1503

**Closed by mstormi** 2021-05-04 13:29 UTC

**Comment by marcelser** [comment] 2021-05-04 13:46
Ok, but how should somebody know that he needs to run "install/upgrade OH" as there's no warning or popup or something that tells you that you need to run that first to make the

**Comment by marcelser** [comment] 2021-05-04 13:48
Ok, I tried running "upgrad/install OH" now. But it fails adding the publicKey. So I turned on debugging and found out that the link for the public key is downloaded from:
https://bintray.com/user/downloadSubjectPublicKey?username=openhab

When you try that you get a 404. So the switch from bintray to artifactory is not working

**Comment by Diapolo** [comment] 2021-05-05 17:32
Seems there is something not correct. I got a self-update on OH3 branch for openhabian-config and after a manual "sudo apt-get update" I get this:

> Hit:1 http://archive.raspberrypi.org/debian buster InRelease
Hit:2 http://raspbian.raspberrypi.org/raspbian buster InRelease                                                                      
Hit:3 https://packages.grafana.com/oss/deb stable InRelease                                                                          
Hit:4 https://deb.nodesource.com/node_14.x buster InRelease                                                    
Hit:5 https://repos.influxdata.com/debian buster InRelease                                    
Hit:6 https://openhab.jfrog.io/artifactory/openhab-linuxpkg stable InRelease
Reading package lists... Done
W: Target Packages (main/binary-armhf/Packages) is configured multiple times in /etc/apt/sources.list.d/openhab-linuxpkg.list:7 and /etc/apt/sources.list.d/openhab.list:1
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/openhab-linuxpkg.list:7 and /etc/apt/sources.list.d/openhab.list:1
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list.d/openhab-linuxpkg.list:7 and /etc/apt/sources.list.d/openhab.list:1
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/openhab-linuxpkg.list:7 and /etc/apt/sources.list.d/openhab.list:1
W: Target Translations (main/i18n/Translation-en_US.UTF-8) is configured multiple times in /etc/apt/sources.list.d/openhab-linuxpkg.list:7 and /etc/apt/sources.list.d/openhab.list:1
W: Target Packages (main/binary-armhf/Packages) is configured multiple times in /etc/apt/sources.list.d/openhab-linuxpkg.list:7 and /etc/apt/sources.list.d/openhab.list:1
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/openhab-linuxpkg.list:7 and /etc/apt/sources.list.d/openhab.list:1
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list.d/openhab-linuxpkg.list:7 and /etc/apt/sources.list.d/openhab.list:1
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/openhab-linuxpkg.list:7 and /etc/apt/sources.list.d/openhab.list:1
W: Target Translations (main/i18n/Translation-en_US.UTF-8) is configured multiple times in /etc/apt/sources.list.d/openhab-linuxpkg.list:7 and /etc/apt/sources.list.d/openhab.list:1

**Comment by Diapolo** [comment] 2021-05-05 17:35
I need to add that there was a file called "etc/apt/sources.list.d/openhab.list**e**", which I removed manually, as it was the old bintray repo as far as I could tell...

**Comment by mstormi** [comment] 2021-05-05 20:50
If you have a repo more than once in your files this is what you get.
That's not an openHABian problem but yours, you have created those duplicates.

**Comment by Diapolo** [comment] 2021-05-06 13:54
Dear @mstormi, it IS indeed an openHABian problem as I don't even know how to create duplicates and such. The current state is a result of just using openhabian-config and doing tweaks, upgrades and stuff with it. So how can I fix this?

**Comment by mstormi** [comment] 2021-05-06 14:01
It is NOT an openHABian problem as there's no code in there to create such duplicates.
Maybe there has been long ago, maybe it was some other software, maybe it was you. But today there is not.
Just comment out one of the duplicate lines. BTW it's just a warning so does not even need to be fixed.
