### ISSUE TITLE
Installation status stays blank

### ISSUE THREAD

**Issue by jakobjp** [openhab/openhabian#1075] opened 2020-08-03 12:36 UTC
During fresh installation of openhabian on RPI 3B+ the web-based status stays blank. No updates, even on manual browser refresh. Nothing.

Attached screenshot 1 from browser.
Attached screenshot 2 from SSH (same time).

Image used:
openhabian-pi-raspbian-201908050414-gitca0976f-crc6a66b5a1.img.xz

<img width="790" alt="Screenshot 2020-08-03 at 14 31 35" src="https://user-images.githubusercontent.com/775512/89182836-a3509780-d596-11ea-8326-ff1c8750cd86.png">

<img width="685" alt="Screenshot 2020-08-03 at 14 33 33" src="https://user-images.githubusercontent.com/775512/89182847-a6e41e80-d596-11ea-8637-d761b3e756ba.png">

At the end, the setup succeeds within a normal timeframe (approximately 20 min), with the following SSH screenshot: (Still empty web-based log.)

<img width="575" alt="Screenshot 2020-08-03 at 14 40 10" src="https://user-images.githubusercontent.com/775512/89183362-65a03e80-d597-11ea-9ea7-295c12e5464f.png">

**Comment by ecdye** [comment] 2020-08-03 15:27
That is likely caused by changes to the install process we have made and should be fixed in the next image release.

**Comment by mstormi** [comment] 2020-08-03 16:13
> That is likely caused by changes to the install process we have made

Which ones?
For me it's been working fine,

**Comment by ecdye** [comment] 2020-08-04 15:07
I rewrote and changed the install webserver with the FIND3 changes, which involved renaming the file, that might have caused it.

**Comment by mstormi** [comment] 2020-08-04 15:31
just installed another instance and it displayed fine.
Did you already fix it or what's left to fix?

**Comment by ecdye** [comment] 2020-08-04 16:57
Did you use the most recent image or 1.5? This bug is from 1.5

**Comment by mstormi** [comment] 2020-08-04 20:11
> Did you use the most recent image or 1.5? This bug is from 1.5

yes, see OP.
So I'll close this issue as that's fixed in the upcoming image (and the alpha one).

**Closed by mstormi** 2020-08-04 20:11 UTC
