### ISSUE TITLE
InfluxDB / Grafana Installation Error - failed to initialize SQL engine

### ISSUE THREAD

**Issue by Goldich** [openhab/openhabian#920] opened 2020-05-26 19:04 UTC
Hi,
I just tried to install InfluxDB / Grafana via `openhabian-config` and failed. I'm running the latest openHABian on a Raspberry 4. 

Here the entire log of the installation.

```
[20:46:27] openhabian@openhab:~$ sudo openhabian-config
2020-05-26_20:47:18_CEST [openHABian] Checking for root privileges... OK
2020-05-26_20:47:18_CEST [openHABian] Updating Linux package information ... 2020-05-26_20:47:18_CEST [openHABian] Loading configuration file '/etc/openhabian.conf'... OK
2020-05-26_20:47:18_CEST [openHABian] openHABian configuration tool version: [master]v1.5-608(1e3c416)
2020-05-26_20:47:18_CEST [openHABian] Checking for changes in origin... OK
2020-05-26_20:47:39_CEST [openHABian] Updating Linux package information ... 2020-05-26_20:47:39_CEST [openHABian] Setting up InfluxDB and Grafana...
openHAB is not running. InfluxDB and grafana openHAB integration is skipped...

Installing InfluxDB...
--2020-05-26 20:50:54--  https://repos.influxdata.com/influxdb.key
Resolving repos.influxdata.com (repos.influxdata.com)... 2600:9000:2047:fc00:7:7790:e740:93a1, 2600:9000:2047:d600:7:7790:e740:93a1, 2600:9000:2047:3a00:7:7790:e740:93a1, ...
Connecting to repos.influxdata.com (repos.influxdata.com)|2600:9000:2047:fc00:7:7790:e740:93a1|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3108 (3.0K) [application/pgp-keys]
Saving to: ‘STDOUT’

-                                                           100%[========================================================================================================================================>]   3.04K  --.-KB/s    in 0s

2020-05-26 20:50:54 (97.7 MB/s) - written to stdout [3108/3108]

OK

$ apt-get update
Get:1 http://archive.raspberrypi.org/debian buster InRelease [25.1 kB]
Hit:2 http://raspbian.raspberrypi.org/raspbian buster InRelease
Ign:3 https://dl.bintray.com/openhab/apt-repo2 stable InRelease
Get:4 https://dl.bintray.com/openhab/apt-repo2 stable Release [6,051 B]
Get:5 https://repos.influxdata.com/debian buster InRelease [4,731 B]
Get:7 https://repos.influxdata.com/debian buster/stable armhf Packages [929 B]
Fetched 36.8 kB in 2s (24.4 kB/s)
Reading package lists... Done

$ apt-get -y install influxdb
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  rpi.gpio-common triggerhappy
Use 'sudo apt autoremove' to remove them.
The following NEW packages will be installed:
  influxdb
0 upgraded, 1 newly installed, 0 to remove and 5 not upgraded.
Need to get 59.1 MB of archives.
After this operation, 151 MB of additional disk space will be used.
Get:1 https://repos.influxdata.com/debian buster/stable armhf influxdb armhf 1.8.0-1 [59.1 MB]
Fetched 59.1 MB in 11s (5,586 kB/s)
Selecting previously unselected package influxdb.
(Reading database ... 47712 files and directories currently installed.)
Preparing to unpack .../influxdb_1.8.0-1_armhf.deb ...
Unpacking influxdb (1.8.0-1) ...
Setting up influxdb (1.8.0-1) ...
Created symlink /etc/systemd/system/influxd.service → /lib/systemd/system/influxdb.service.
Created symlink /etc/systemd/system/multi-user.target.wants/influxdb.service → /lib/systemd/system/influxdb.service.
Processing triggers for man-db (2.8.5-2) ...
Updating FireMotD available updates count ...

$ sed -i s/auth-enabled = true/# auth-enabled = false/g /etc/influxdb/influxdb.conf

$ systemctl daemon-reload

$ systemctl enable influxdb.service

$ systemctl restart influxdb.service
OK Configure InfluxDB admin account... {"results":[{"statement_id":0}]}
{"results":[{"statement_id":0}]}
OK Configure listen on localhost only...
$ sed -i -e /# Determines whether HTTP endpoint is enabled./ { n ; s/# enabled = true/enabled = true/ } /etc/influxdb/influxdb.conf

$ sed -i s/# bind-address = ":8086"/bind-address = "localhost:8086"/g /etc/influxdb/influxdb.conf

$ sed -i s/# auth-enabled = false/auth-enabled = true/g /etc/influxdb/influxdb.conf

$ sed -i s/# store-enabled = true/store-enabled = false/g /etc/influxdb/influxdb.conf

$ systemctl restart influxdb.service
OK Waiting for InfluxDB service... OK
Setup of inital influxdb database and InfluxDB users... {"results":[{"statement_id":0}]}
{"results":[{"statement_id":0}]}
{"results":[{"statement_id":0}]}
{"results":[{"statement_id":0}]}
{"results":[{"statement_id":0}]}
{"results":[{"statement_id":0}]}
{"results":[{"statement_id":0}]}
OK Installing Grafana... --2020-05-26 20:51:32--  https://packages.grafana.com/gpg.key
Resolving packages.grafana.com (packages.grafana.com)... 2a04:4e42:3::729, 151.101.14.217
Connecting to packages.grafana.com (packages.grafana.com)|2a04:4e42:3::729|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1694 (1.7K) [application/x-iwork-keynote-sffkey]
Saving to: ‘STDOUT’

-                                                           100%[========================================================================================================================================>]   1.65K  --.-KB/s    in 0s

2020-05-26 20:51:32 (6.84 MB/s) - written to stdout [1694/1694]

OK

$ apt-get update
Hit:1 http://raspbian.raspberrypi.org/raspbian buster InRelease
Get:2 http://archive.raspberrypi.org/debian buster InRelease [25.1 kB]
Hit:3 https://repos.influxdata.com/debian buster InRelease
Ign:4 https://dl.bintray.com/openhab/apt-repo2 stable InRelease
Get:5 https://dl.bintray.com/openhab/apt-repo2 stable Release [6,051 B]
Get:6 https://packages.grafana.com/oss/deb stable InRelease [12.1 kB]
Get:8 https://packages.grafana.com/oss/deb stable/main armhf Packages [16.6 kB]
Fetched 59.9 kB in 2s (32.4 kB/s)
Reading package lists... Done

$ apt-get -y install grafana
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  rpi.gpio-common triggerhappy
Use 'sudo apt autoremove' to remove them.
The following NEW packages will be installed:
  grafana
0 upgraded, 1 newly installed, 0 to remove and 5 not upgraded.
Need to get 41.7 MB of archives.
After this operation, 121 MB of additional disk space will be used.
Get:1 https://packages.grafana.com/oss/deb stable/main armhf grafana armhf 7.0.1 [41.7 MB]
Fetched 41.7 MB in 7s (5,714 kB/s)
Selecting previously unselected package grafana.
(Reading database ... 47738 files and directories currently installed.)
Preparing to unpack .../grafana_7.0.1_armhf.deb ...
Unpacking grafana (7.0.1) ...
Setting up grafana (7.0.1) ...
Adding system user `grafana' (UID 111) ...
Adding new user `grafana' (UID 111) with group `grafana' ...
Not creating home directory `/usr/share/grafana'.
### NOT starting on installation, please execute the following statements to configure grafana to start automatically using systemd
 sudo /bin/systemctl daemon-reload
 sudo /bin/systemctl enable grafana-server
### You can start grafana-server by executing
 sudo /bin/systemctl start grafana-server
Processing triggers for systemd (241-7~deb10u4+rpi1) ...
Updating FireMotD available updates count ...

$ systemctl daemon-reload

$ systemctl enable grafana-server.service
Synchronizing state of grafana-server.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable grafana-server
Created symlink /etc/systemd/system/multi-user.target.wants/grafana-server.service → /usr/lib/systemd/system/grafana-server.service.

$ systemctl start grafana-server.service
OK
Resetting Grafana admin password...
$ grafana-cli admin reset-admin-password admin
INFO[05-26|20:52:01] Connecting to DB                         logger=sqlstore dbtype=sqlite3
INFO[05-26|20:52:01] Starting DB migration                    logger=migrator
INFO[05-26|20:52:03] Database locked, sleeping then retrying  logger=sqlstore error="database is locked" retry=0
INFO[05-26|20:52:03] Database locked, sleeping then retrying  logger=sqlstore error="database is locked" retry=1
INFO[05-26|20:52:03] Database locked, sleeping then retrying  logger=sqlstore error="database is locked" retry=2
INFO[05-26|20:52:03] Database locked, sleeping then retrying  logger=sqlstore error="database is locked" retry=3
INFO[05-26|20:52:03] Database locked, sleeping then retrying  logger=sqlstore error="database is locked" retry=4
INFO[05-26|20:52:03] Database locked, sleeping then retrying  logger=sqlstore error="database is locked" retry=5
INFO[05-26|20:52:03] Database locked, sleeping then retrying  logger=sqlstore error="database is locked" retry=6
INFO[05-26|20:52:03] Database locked, sleeping then retrying  logger=sqlstore error="database is locked" retry=7
INFO[05-26|20:52:03] Database locked, sleeping then retrying  logger=sqlstore error="database is locked" retry=8
INFO[05-26|20:52:03] Database locked, sleeping then retrying  logger=sqlstore error="database is locked" retry=9
INFO[05-26|20:52:03] Database locked, sleeping then retrying  logger=sqlstore error="database is locked" retry=10
INFO[05-26|20:52:03] Database locked, sleeping then retrying  logger=sqlstore error="database is locked" retry=11
INFO[05-26|20:52:03] Database locked, sleeping then retrying  logger=sqlstore error="database is locked" retry=12
INFO[05-26|20:52:03] Database locked, sleeping then retrying  logger=sqlstore error="database is locked" retry=13
Error: ✗ failed to initialize SQL engine: Failed to create admin user: UNIQUE constraint failed: user.email
FAILED Connection Grafana to InfluxDB...curl: (7) Failed to connect to localhost port 3000: Connection refused
Adding openHAB dashboard tile for Grafana... 2020-05-26_20:52:04_CEST [openHABian] Adding an openHAB dashboard tile for 'grafana'... OK
```

**Comment by holgerfriedrich** [comment] 2020-05-26 19:41
Hi, thanks for reporting.
It might be a duplicate of #914, so please be patient until #915 is merged.
Then try removing grafana `sudo apt purge grafana`, possibly delete `/var/lib/grafana`.
Then try again.

**Closed** 2020-05-27 08:37 UTC
Labels: bug-regression, optional component
