### ISSUE TITLE
Grafana & InfluxDB install fails. 

### ISSUE THREAD

**Issue by MaRRiK74** [openhab/openhabian#1103] opened 2020-08-27 21:07 UTC
Running on a raspberry PI 3 with latest (minimal) image.

When trying to install Grafana and InfluxDB, a lot of GPG errors are shown. After adding GPG keys manually and checked for GPG errors with apt-update, and restarting openhabian-config it still won't work.

Grafana and Influx will get installed but configuration fails.
When starting the install the following is shown:

Installing InfluxDB...
gpg: no valid OpenPGP data found.
FAILED Configure InfluxDB admin account... {"results":[{"statement_id":0}]}
{"results":[{"statement_id":0}]}
FAILED Configure listen on localhost only... FAILED Waiting for InfluxDB service... FAILED Setup of inital influxdb database and InfluxDB users... curl: (7) Failed to connect to localhost port 8086: Connection refused
curl: (7) Failed to connect to localhost port 8086: Connection refused
curl: (7) Failed to connect to localhost port 8086: Connection refused
{"results":[{"statement_id":0}]}
{"results":[{"statement_id":0}]}
{"results":[{"statement_id":0,"error":"user not found"}]}
{"results":[{"statement_id":0,"error":"database not found: openhab_db"}]}
FAILED Installing Grafana... gpg: no valid OpenPGP data found.
FAILED
Thu 27 Aug 22:54:18 CEST 2020
---
---
DEBUG  6281 /usr/sbin/grafana-server --config=/etc/grafana/grafana.ini --pidfile=/var/run/grafana/grafana-server.pid --packaging=deb cfg:default.paths.logs=/var/log/grafana cfg:default.paths.data=/var/lib/grafana cfg:default.paths.plugins=/var/lib/grafana/plugins cfg:default.paths.provisioning=/etc/grafana/provisioning
---

Connection Grafana to InfluxDB...{"datasource":{"id":2,"orgId":1,"name":"openhab_home","type":"influxdb","typeLogoUrl":"","access":"proxy","url":"http://localhost:8086","password":"xxxxxxxxxxxx","user":"grafana","database":"openhab_db","basicAuth":true,"basicAuthUser":"grafana","basicAuthPassword":"xxxxxxxxxxx","withCredentials":false,"isDefault":false,"jsonData":{},"secureJsonFields":{},"version":1,"readOnly":false},"id":2,"message":"Datasource added","name":"openhab_home"}Adding openHAB dashboard tile for Grafana... 2020-08-27_22:54:19_CEST [openHABian] Adding an openHAB dashboard tile for 'grafana'... Replacing... OK
Adding install InfluxDB with database configuration to openHAB<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.14.2</center>
</body>
</html>

Maybe this can could related (repo change and maybe outdated in openhabian-config?):
https://community.grafana.com/t/upgrade-public-key-is-not-available-error/13881

**Comment by mstormi** [comment] 2020-09-04 19:38
I'm afraid I cannot reproduce your problem on a fresh openhabian install.
So it was either temporary or your key storage is messed up.
Check your repo, purge and try installing again

```
[21:33:55] root@openhab:/etc/apt/sources.list.d# cat influxdb.list
deb https://repos.influxdata.com/debian buster stable
[21:33:59] root@openhab:/etc/apt/sources.list.d# cat grafana.list
deb https://packages.grafana.com/oss/deb stable main
```

**Comment by pjpeartree** [comment] 2020-09-08 12:42
Same issue at my side, using the latest openHABian system image 2.5.8 on raspberry PI 4.

`2020-09-08_13:27:17_WEST [openHABian] Setting up InfluxDB and Grafana...
2020-09-08_13:27:47_WEST [openHABian] Setting openHAB HTTP/HTTPS ports... OK
Installing InfluxDB...
gpg: no valid OpenPGP data found.
FAILED Configure InfluxDB admin account... {"results":[{"statement_id":0}]}
{"results":[{"statement_id":0}]}
FAILED Configure listen on localhost only... FAILED Waiting for InfluxDB service... FAILED Setup of inital influxdb database and InfluxDB users... {"results":[{"statement_id":0}]}
{"results":[{"statement_id":0}]}
{"results":[{"statement_id":0}]}
{"results":[{"statement_id":0}]}
{"results":[{"statement_id":0}]}
{"results":[{"statement_id":0}]}
{"results":[{"statement_id":0}]}
FAILED Installing Grafana... gpg: no valid OpenPGP data found.
gpg: no valid OpenPGP data found.FAILED
Tue  8 Sep 13:28:41 WEST 2020
---
---
DEBUG  7452 /usr/sbin/grafana-server --config=/etc/grafana/grafana.ini --pidfile=/var/run/grafana/grafana-server.pid --packaging=deb cfg:default.paths.logs=/var/log/grafana cfg:default.paths.data=/var/lib/grafana cfg:default.paths.plugins=/var/lib/grafana/plugins cfg:default.paths.provisioning=/etc/grafana/provisioning
---

**Comment by benlinkels** [comment] 2020-09-11 18:31
I have the same issue - fresh install of openHAB on Ubuntu 20.04. Adding InfluxDB+Grafana with the openhabian-config results in an Error message regarding missing gpg data.

Running `sudo apt update` show that the keys for the repositories are missing.

```
W: GPG error: https://packages.grafana.com/oss/deb stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 8C8C34C524098CB6
E: The repository 'https://packages.grafana.com/oss/deb stable InRelease' is not signed.

W: GPG error: https://repos.influxdata.com/ubuntu focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 684A14CF2582E0C5
E: The repository 'https://repos.influxdata.com/ubuntu focal InRelease' is not signed.
```

Added the signatures manually:
```
wget -q -O - https://packages.grafana.com/gpg.key | sudo apt-key add -
wget -qO- https://repos.influxdata.com/influxdb.key | sudo apt-key add -
```
`sudo apt update` is running now without further warning or error


I am still not able to add InfluxDB+Grafana with the openhabian-config tool thoug
```
[20:23:36] chef@hab:~$ sudo openhabian-config 
2020-09-11_20:23:41_CEST [openHABian] Checking for root privileges... OK
2020-09-11_20:23:41_CEST [openHABian] Loading configuration file '/etc/openhabian.conf'... OK
2020-09-11_20:23:41_CEST [openHABian] openHABian configuration tool version: [stable]v1.6-alpha-755(0290f04)
2020-09-11_20:23:41_CEST [openHABian] Checking for changes in origin branch stable... OK
2020-09-11_20:23:43_CEST [openHABian] Switching to branch stable... OK
2020-09-11_20:23:49_CEST [openHABian] Updating Linux package information... OK
2020-09-11_20:23:49_CEST [openHABian] Setting up InfluxDB and Grafana... 
2020-09-11_20:24:23_CEST [openHABian] Setting openHAB HTTP/HTTPS ports... OK
Installing InfluxDB...
gpg: no valid OpenPGP data found.
FAILED Configure InfluxDB admin account... {"results":[{"statement_id":0}]}
{"results":[{"statement_id":0}]}
FAILED Configure listen on localhost only... FAILED Waiting for InfluxDB service... FAILED Setup of inital influxdb database and InfluxDB users... {"results":[{"statement_id":0}]}
{"results":[{"statement_id":0}]}
{"results":[{"statement_id":0}]}
{"results":[{"statement_id":0}]}
{"results":[{"statement_id":0}]}
{"results":[{"statement_id":0}]}
{"results":[{"statement_id":0}]}
FAILED Installing Grafana... gpg: no valid OpenPGP data found.
FAILED 
Fri 11 Sep 2020 08:24:39 PM CEST
---
---
DEBUG  798 /usr/sbin/grafana-server --config=/etc/grafana/grafana.ini --pidfile=/var/run/grafana/grafana-server.pid --packaging=deb cfg:default.paths.logs=/var/log/grafana cfg:default.paths.data=/var/lib/grafana cfg:default.paths.plugins=/var/lib/grafana/plugins cfg:default.paths.provisioning=/etc/grafana/provisioning
---

Connection Grafana to InfluxDB...{"message":"Invalid username or password"}Adding openHAB dashboard tile for Grafana... 2020-09-11_20:24:40_CEST [openHABian] Adding an openHAB dashboard tile for 'grafana'... Replacing... OK
Adding install InfluxDB with database configuration to openHABcurl: (7) Failed to connect to localhost port 80: Connection refused
2020-09-11_20:24:45_CEST [openHABian] We hope you got what you came for! See you again soon ;)
```

**Comment by HerzScheisse** [comment] 2020-09-11 20:58
Hi I have the exakt same error like @benlinkels stated... with the same error messages on a very fresh openhabian alpha install on the master branch.

**Comment by ecdye** [comment] 2020-09-12 00:24
A fix is coming, it should work after #1055 is merged. I'll try to have it in before the end of next week.

**Comment by HerzScheisse** [comment] 2020-09-14 12:06
I can confirm that the grafana and influxdb setup via openhabian config is working now...

**Closed** 2020-09-14 14:06 UTC

**Comment by benlinkels** [comment] 2020-09-15 17:45
Hello @HerzScheisse 
How did you mange to do that?

Steps from my side:

1. Update openhabian with '02 | Upgrade System" and checked on '/opt/openhabian' with 'git status'
2. purged influxdb and grafana 'sudo apt purge influxdb grafana'
3. cleaned the config directories 'sudo rm -rf /var/lib/influxdb/' and 'sudo rm -rf /etc/grafana/'
4. Tried to install '24 InfluxDB+Grafana' with the openhabian-config

```
[19:35:56] chef@hab:~$ sudo openhabian-config --verbose
2020-09-15_19:35:58_CEST [openHABian] Checking for root privileges... OK
2020-09-15_19:35:58_CEST [openHABian] Loading configuration file '/etc/openhabian.conf'... OK
2020-09-15_19:35:58_CEST [openHABian] openHABian configuration tool version: [stable]patchday-20200912-805(12917d6)
2020-09-15_19:35:58_CEST [openHABian] Checking for changes in origin branch stable... OK
2020-09-15_19:36:00_CEST [openHABian] Switching to branch stable... OK
2020-09-15_19:36:03_CEST [openHABian] Updating Linux package information... OK
2020-09-15_19:36:03_CEST [openHABian] Setting up InfluxDB and Grafana... 
2020-09-15_19:36:34_CEST [openHABian] Setting openHAB HTTP/HTTPS ports... OK
Installing InfluxDB...
gpg: no valid OpenPGP data found.
FAILED Configure InfluxDB admin account... {"results":[{"statement_id":0,"error":"user already exists"}]}
{"results":[{"statement_id":0}]}
FAILED Configure listen on localhost only... FAILED Waiting for InfluxDB service... FAILED Setup of inital influxdb database and InfluxDB users... {"results":[{"statement_id":0}]}
{"results":[{"statement_id":0}]}
{"results":[{"statement_id":0}]}
{"results":[{"statement_id":0}]}
{"results":[{"statement_id":0}]}
{"results":[{"statement_id":0}]}
{"results":[{"statement_id":0}]}
FAILED Installing Grafana... gpg: no valid OpenPGP data found.
FAILED 
Tue 15 Sep 2020 07:36:55 PM CEST
---
---
DEBUG  798 /usr/sbin/grafana-server --config=/etc/grafana/grafana.ini --pidfile=/var/run/grafana/grafana-server.pid --packaging=deb cfg:default.paths.logs=/var/log/grafana cfg:default.paths.data=/var/lib/grafana cfg:default.paths.plugins=/var/lib/grafana/plugins cfg:default.paths.provisioning=/etc/grafana/provisioning
---

Connection Grafana to InfluxDB...{"message":"Invalid username or password"}Adding openHAB dashboard tile for Grafana... 2020-09-15_19:36:55_CEST [openHABian] Adding an openHAB dashboard tile for 'grafana'... Replacing... OK
Adding install InfluxDB with database configuration to openHABcurl: (7) Failed to connect to localhost port 80: Connection refused
2020-09-15_19:37:01_CEST [openHABian] We hope you got what you came for! See you again soon ;)

```

**Comment by ecdye** [comment] 2020-09-15 18:58
You have to be on the master branch, as the newest changes have not been added to the stable branch yet.

**Comment by HerzScheisse** [comment] 2020-09-15 20:12
> How did you mange to do that?

As @ecdye mentioned you need to be on the master branch...

But even if, i got a error (dont remember the exakt error message) when upgrading via openhabian-config

So i did a manual:
`sudo apt update`
`sudo apt upgrade` error that i nee to configure 2 files
`sudo dpkg --configure -a`
`sudo apt upgrade`
