### ISSUE TITLE
add a delay and/or check the network is active prior to issue the apt-update

### ISSUE THREAD

**Issue by thedannymullen** [openhab/openhabian#441] opened 2018-09-14 20:55 UTC
When installing using wifi, I have found that the install fails at apt-update.  I modified the first-boot.sh on line 80 adding a sleep and everything seemed to work great.  

Prior to adding the sleep, this command would routinely fail.  Hardware this failed and was tested on was Raspberri Pi 3 model b.  

[first-boot.log](https://github.com/openhab/openhabian/files/2384857/first-boot.log)

[first-boot.sh.txt](https://github.com/openhab/openhabian/files/2384868/first-boot.sh.txt)

It looks as if the logic here: 
`echo -n "$(timestamp) [openHABian] Waiting for dpkg/apt to get ready... "
until apt update &>/dev/null; do sleep 1; done
echo "OK"
`
Is this supposed to possibly check for network to be online?  If so there seems to be some error doing so.  However putting a sleep in solved the problem.  **Please let me know** if you need more information or would like me to make any modifications.  I attached my modified file that worked for me.

**Comment by EliasGabrielsson** [comment] 2018-09-20 09:07
Hi Danny and thanks for the report.
If it's solves your problem we shall absolutely add some sleep time.
Have you tried out more aggressive sleep time, eg. `5` or does it need to be `10`?

**Comment by thedannymullen** [comment] 2018-09-29 02:01
I tried 5, I can’t remember if that worked or not.  In the end I decided on 10 as openhabian is headless install.  I figured 10 seconds would not be noticed.

**Comment by thedannymullen** [comment] 2018-11-02 00:34
@EliasGabrielsson  more info on this.  I did some more debug trying to find the error.  I changed &>/dev/null to 1>/dev/null 2>/boot/update.log on the apt-get statement.  When doing that it does not fail.  I tried printing everything out and received no failures also.  

I also added google public dns to my setup and tried to install.  That experiment was inconclusive as I had some other error.  Not related to apt.  I would need to repeat this again, but have not tried yet.

This seems to confirm a timing issue of some type as when you send &>/dev/null it fails repeatedly.  I wonder instead of a delay like originally requested could we add 2>somelogfile this would allow the community to log errors.  Maybe we can get more details.

**Comment by ThomDietrich** [comment] 2018-12-19 12:44
Hey guys! There is no real harm in adding a short sleep... however I don't understand the reason for it. The script checks for an internet connection, then checks for apt/dpkg to become ready. If the second check is not fully doing what it is supposed to do, I wonder if that could be fixed instead...
Yet again I recognize that @thedannymullen tried to find the cause of the problem and that turned out to be a tough one. @thedannymullen do you think the PR represents the best solution we can come up with?

**Closed** 2018-12-26 13:36 UTC
Labels: bug
