### ISSUE TITLE
OH3 install, a few folders are wrong

### ISSUE THREAD

**Issue by schossel** [openhab/openhabian#1324] opened 2020-12-23 19:49 UTC
I tried to install OH3 on a Debian virtual machine. That worked quite well except that a few folders in scripts were not correct.

The frontail installation ends with:
`Adding an openHAB dashboard tile for 'frontail'... FAILED (openHAB or config folder missing)`
because the function /functions/openhab.bash/dashboard_add_tile() has /etc/openhab2 hardcoded. 

The same goes for /etc/systemd/system/frontail.service (Perhaps not your problem), all the openhab2 paths have to be changed and the frontail service has to be restarted to work correctly.

After installing samba with the openhabian-config, it's not working because the permissions are still wrong. 
The function in /functions/system.bash/permissions_corrections() has also a few wrong paths to openhab2.

I corrected these manually and everything seems to work. Perhaps, after the main installation, the scripts should check first which version was installed?

**Comment by mstormi** [comment] 2020-12-23 20:37
This is 2 different issues. First (dashboard) is a duplicate of #1316.

Second isn't about what you report. You likely didn't switch to the openHAB3 branch of openHABian after migration. That one will not exhibit the behavior you report.
If possible please report (with a log, set debugmode=maximum) what was your starting point and which were the steps you took to install or upgrade OH that made you end up in this state.

**Comment by schossel** [comment] 2020-12-23 21:20
I installed it again and you're right, to chose the branch is not mandatory and so I skipped it. This leads further along during the installation to the point that openhab2 paths are used but OH3 is installed.
Nevertheless, even when chosing the right branch (OH3), the permissions function does not finish OK. Error is :
2020-12-23_22:10:02_CET [openHABian] Applying file permissions recommendations... FAILED (3rd party logdir).
Frontail and Samba worked.

**Comment by mstormi** [comment] 2020-12-23 22:25
> I installed it again and you're right, to chose the branch is not mandatory and so I skipped it.

Well it *is* mandatory. Why do you think it isn't ?

>  I don't know why, I did nothing other than turning the log level up.

... and restarting, resulting in an openhabian update, again being asked to choose your branch, right ?

> So, when chosing the right branch it seems to work. Perhaps it would be a good idea to show that somehow. I didn't even see teh possibility to chose the OH3 branch!?
err .. option 01 ?

To me, the way more interesting question (to prevent this from happening to others too) is: 
- what was your starting point? (openhabian version and branch, openhab version, when did you upgrade openhabian ?) and 
- which steps did you apply to upgrade ? Did that change the branch ? If yes, did you change back ? and if so: why the heck ? Was there any docs telling you so ?

**Comment by schossel** [comment] 2020-12-23 22:32
I did a clean install of Debian and followed this guide: https://www.openhab.org/docs/installation/openhabian.html#other-linux-systems-add-openhabian-just-like-any-other-software
At some point sudo openhabian-config should be performed which I did. Then, for me, it was not clear that I have to chose a branch because I wanted to test OH3 and somewhere it was mentioned that it is the default option, so I did nothing there. This lead to the fact that OH3 was installed but some scripts did not work because I did not explicitly chose branch=OH3.
I did not upgrade from somewhere.

**Comment by mstormi** [comment] 2020-12-23 22:40
> I did a clean install of Debian and followed this guide: https://www.openhab.org/docs/installation/openhabian.html#other-linux-systems-add-openhabian-just-like-any-other-software

Right that says to clone the stable branch. It has been fixed but the docs website has not been updated yet.
@Confectrician your turn please

> somewhere it was mentioned that it is the default option,

Where exactly ? I'm not asking to blame you but to find the docs that eventually need fixing.
Did you not notice option 03 ?

**Comment by schossel** [comment] 2020-12-23 22:48
I read it somewhere. It was not in that specific guide. I think what you can't understand is that I never opened Point 01 and didn't even have a look at what options there are to chose. I had in my mind that OH3 is now default and therefore I never thought about to chose a branch. The problem is (IMO) that you can do that, there's no warning that without chosing a branch, OH3 will be installed but the scripts running in the background will fail because they think it should be OH2. Somewehere it should say "You have to chose a branch by 01 before proceeding".

**Comment by Confectrician** [comment] 2020-12-23 23:09
Website build may need one or two days. We have some other issues as well that should get fixed aside.

I will trigger one of I am not able to fix the other issues today (24th)

**Comment by mstormi** [comment] 2020-12-23 23:10
Well yes I cannot understand when someone is blindly selecting an option without reading the menu and the docs first.
But as I said this is not to blame you but to find the docs.

You should not need to select the branch because that should happen automatically.
If you had selected option 03 it should have done that for you.
How exactly did you select to install OH if not via 03 ?

The problem is there are many different starting points and pathes that all lead to Rome but a dev or docs writer cannot cater for all of them let alone for users making assumptions where they should not (i.e. any sort of "I read it somewhere" which may be right or wrong).

**Comment by mstormi** [comment] 2020-12-23 23:12
> Website build may need one or two days

Can't you just manually replace the branch name ?

**Comment by Confectrician** [comment] 2020-12-24 08:37
No, sorry. It's not that easy.

The build is automated with our host "netlify" which gets triggered, fetches the up to date contents from github, runs the script to generate the vuepress site (thats our website application) and publishes and delivers it.
There is simply no place or folder structure where i can edit one word.

But as said i will anyhow trigger a build if my progress doesn't get as far as i want to.

**Comment by schossel** [comment] 2020-12-24 11:38
Just a quick update. I installed it a few times over now, to get it running error free. These are the commands I had to run on a fresh Debian:
su
apt-get install sudo openjdk-11-jdk gnupg2 git 
wget -qO - 'https://bintray.com/user/downloadSubjectPublicKey?username=openhab' | sudo apt-key add -
git clone -b stable https://github.com/openhab/openhabian.git /opt/openhabian
ln -s /opt/openhabian/openhabian-setup.sh /usr/local/bin/openhabian-config
cp /opt/openhabian/openhabian.conf.dist /etc/openhabian.conf
nano /etc/sudoers //add user (in my case test) to sudoers test ALL=(ALL:ALL) ALL
nano /etc/openhabian.conf //set debugmode=on or maximum
exit
sudo bash
sudo openhabian-config
select branch OH3 
Follow all other point all the way down.

This works until "Apply Improvements" - "Fix permissions". This fails with "FAILED (3rd party logdir)"
`2020-12-24_12:24:18_CET [openHABian] Applying file permissions recommendations...
$ usermod --append --groups audio openhab

$ usermod --append --groups audio openhabian

$ usermod --append --groups dialout openhab

$ usermod --append --groups dialout openhabian

$ usermod --append --groups tty openhab

$ usermod --append --groups tty openhabian

$ usermod --append --groups openhab openhabian

$ chown openhab:openhab /srv /srv/README.txt /opt

$ chmod ugo+w /srv /srv/README.txt

$ chown --recursive openhab:openhab /etc/openhab /var/lib/openhab /var/log/openhab /usr/share/openhab

$ chmod --recursive ug+wX /opt /etc/openhab /var/lib/openhab /var/log/openhab /usr/share/openhab

$ chown --recursive openhabian:openhabian /home/openhabian

$ setfacl -R --remove-all /etc/openhab /var/lib/openhab /var/log/openhab /usr/share/openhab

$ setfacl -R -m g::rwX /etc/openhab /var/lib/openhab /var/log/openhab /usr/share/openhab

$ setfacl -R -m d:g::rwX /etc/openhab /var/lib/openhab /var/log/openhab /usr/share/openhab

$ chgrp --silent root /var/log/samba /var/log/unattended-upgrades
FAILED (3rd party logdir)
`
The cause seems to be, that Fix permissions is Point 14 and Samba Installation is Point 16. After I got back into openhabian-config and did the samba installation and got back to Fix the file permissions after that, the log was clear:
$ chgrp --silent root /var/log/samba /var/log/unattended-upgrades
OK

So with this set of instructions it should be possible to install in Debian. The instructions at https://www.openhab.org/docs/installation/openhabian.html#other-linux-systems-add-openhabian-just-like-any-other-software
don't mention that you have to install openjdk-11-jdk gnupg2 git. Without the installation of Java before openhab-config it fails. Without gnupg2 they key command will fail.

This is as far as I can test for today or my wife will kill me.

**Comment by Confectrician** [comment] 2020-12-24 12:39
Next website build is including the docs fixes for openhabian.
Should be available in the next 30min if nothing fails.

**Comment by mstormi** [comment] 2020-12-25 00:22
> don't mention that you have to install openjdk-11-jdk gnupg2 git. Without the installation of Java before openhab-config it fails.

No you wouldn't need to install java
apt-key is not specific to openHABian and should work on your OS (else your OS setup is broken in the first place).
If you run `openhabian-config unattended` it'll install a number of packages including Samba, Java and others.
But you didn't use that, and you obviously also failed to manually install those packages (and nowhere it says you have to do that in a specific order).
Hence the error message is to be expected. But it's not a malfunction.

The install instructions are fixed (live on the website) so IMHO there's nothing left that would need fixing.

**Closed by mstormi** 2020-12-25 00:22 UTC
