### ISSUE TITLE
Node-RED installation as optional component not working

### ISSUE THREAD

**Issue by darkmc80** [openhab/openhabian#258] opened 2017-12-08 06:20 UTC
Hello I’m quite new to openHAB

I installed openhabian on a raspberry pi 3B and made all of my smart components work with it. As I wanted to experiment with rules I tried to install Node-RED via Openhabian configuration tool. Not very successful as I’m getting the following error message

There was an error or interruption during the execution of: "20 Optional Components"
Please try again. Open a Ticket if the error persists: https://github.com/openhab/openhabian/issues3

Im using OpenHAB snapshot 2.2 (because of IKEA Tradfri) but I had the same problem on stable release 2.1.

Thanks a lot

Jan

**Comment by ThomDietrich** [comment] 2017-12-08 10:59
Duplicate of https://github.com/openhab/openhabian/issues/247

(Probably.) Did you run "Update" first?

**Closed** 2017-12-08 10:59 UTC
