### ISSUE TITLE
Can´t install openhabian

### ISSUE THREAD

**Issue by botura** [openhab/openhabian#107] opened 2017-03-05 10:15 UTC
Install keeps booting and never finish.

It looses connectiong retrieving different packages. My internet seens to be ok (my pc doens´t loose connection).

It would be nice if it could restart from the last downloaded package and not all over again.

Log always looks like below (except each time with a different package):

...
P: Validating libbz2-1.0
P: Retrieving liblzma5
wget: can't connect to remote host (189.45.5.90): Connection timed out
E: Couldn't download pool/main/x/xz-utils/liblzma5_5.1.1alpha+20120614-2_armhf.deb!

Oh noes, something went wrong!
You have 10 seconds to hit ENTER to get a shell...

**Comment by botura** [comment] 2017-03-05 12:58
I think that the problem is with this mirror: nbtelecom.com.br

Is there a way to not use this mirror?

**Comment by ThomDietrich** [comment] 2017-03-05 18:02
Hello @botura,
judging by your description this might be a bit tricky. The openHABian unattended netinstall (that's what you've downloaded here) expects a reliable repository, which you sadly don't seem to have with your ISP/location. :(

We could try to fix this somehow but I'd suggest a different approach. There is a second way to install openHABian.

1. Download, flash and boot Raspbian Lite
2. Install openHABian the manual way: http://docs.openhab.org/installation/openhabian.html#manual-setup
  * Execute the five shown commands step by step
  * Inside the "openHABian Configuration Tool" execute in this order: 01, 02, 10, 11a, 12, 13, 10 (yes, again)

That should help you get a full openHABian system in just under an hour.

You might be interested to know, that I've planned a new version of the RPi image, which would then probably also work for you. Next time you'll be successful.

Let me know if it worked, please close the issue after the issue is settled.

**Comment by botura** [comment] 2017-03-05 20:27
Hello @ThomDietrich,

It worked! I had to repeat some steps because my mirror is really instable, but it´s ok now.

Thanks!!!

**Closed** 2017-03-05 20:28 UTC

**Comment by RavDee** [comment] 2017-07-25 12:29
hi @ThomDietrich 
where can i find the below to excecute, dont seem to see it on the screen shot
inside the "openHABian Configuration Tool" execute in this order: 11a, 12, 13,

http://docs.openhab.org/installation/openhabian.html#manual-setup

**Comment by ThomDietrich** [comment] 2017-07-25 12:32
Hello @RavDee,

that's because the issue is two four months old, that's enough to be outdated :) The "Manual Setup contains all steps you need to execute step by step. No need for a special order. Just execute from top to bottom.

**Comment by RavDee** [comment] 2017-07-25 12:41
@ThomDietrich ,
ive tried this with the manual setup - but in openhabian configuration tool 61 and 62 work all the others fail 

also when installing the hassle free version it freezes at updating repositories and upgrading installed packages..

Could it be cause of my isp? should i try install it at a another site?#

any help would be great thank you

**Comment by ThomDietrich** [comment] 2017-07-25 12:47
These should not fail... still, yes your connection or ISP might be a problem. Any chance you could post the command line output of those failures here?
