### ISSUE TITLE
Not booting on new Raspberry Pi Model 3 B+

### ISSUE THREAD

**Issue by philipb232** [openhab/openhabian#350] opened 2018-03-22 11:26 UTC
Hi everyone,

i have a brand-new Model 3 B+ and it seems that openhabian is not working with it.
Rainbow screen comes up and the green LED blinks 8 times, red LED is off.
Regarding to this website (https://elinux.org/R-Pi_Troubleshooting#Red_power_LED_is_blinking), 
this means "SDRAM not recognised. You need newer bootcode.bin/start.elf firmware."

I used release 1.4

**Comment by philipb232** [comment] 2018-03-22 11:31
Replacing the start.elf with the newest Raspian start.elf fixed it.

**Comment by Radu10** [comment] 2018-03-22 21:41
I did have the same problem , and i fix it in the same way :)
I copy the file ,,start.elt'' from Raspbian in to openhabian by replace the existing file 
It seams to work for the moment.
I will come back with update
![image](https://user-images.githubusercontent.com/37674444/37800091-70e66146-2e2a-11e8-8384-a076da556b25.png)

**Comment by mues-lee** [comment] 2018-03-27 23:13
Hi,
one thing I noticed is that while running the firstboot the raspi 3b+ only uses 115 MB RAM, this results in a long waiting time till openhab2 finally is ready at
`$(timestamp) [openHABian] Waiting for openHAB to become ready...`
After the reboot the whole RAM is used

Not sure if this happens is the normal behavior or it is a problem with the 3b+

Best
mues-lee

**Comment by mues-lee** [comment] 2018-03-29 14:28
Hi,

I did a little more testing and the problem was, what a surprise, the outdated firmware data of the image.

@ThomDietrich  
I think it would be good to do a `rpi-update` beginning the installation
when you agree to this idea i would send a PR

Best
mues-lee

**Comment by ThomDietrich** [comment] 2018-03-29 15:24
Imho the easier action to solve both issues is to regenerate the openHABian image (image v1.5).
I'm currently a bit short on time. If I were to generate an image, would you guys be able to test?

**Comment by mues-lee** [comment] 2018-03-29 16:00
Testing would be no problem for me.

also i found that in `system.sh` during `basic-package` installation `rpi-update` gets deleted, may i ask why?

**Comment by Radu10** [comment] 2018-03-29 16:13
Yes , i will make a test .

**Comment by BClark09** [comment] 2018-03-29 17:13
I got myself a new RPI 3b+, and have a bit of time on Saturday to test an image if you need an additional tester.

**Comment by ThomDietrich** [comment] 2018-03-30 09:53
Everyone, I'm building the image now.

@EliasGabrielsson @mues-lee any changes or improvements you want to to add to `first-boot.sh` before image v1.5 is officially released?

**Comment by mues-lee** [comment] 2018-03-30 11:21
i would add an additional `apt update &>/dev/null` in before `/usr/bin/apt -y install git &>/dev/null`
this should make sure we have the right repository data, in case the previous `apt upgrade` has updated the repository data

**Comment by ThomDietrich** [comment] 2018-03-30 11:34
The "in case" here is imho not a realistic scenario but it wouldn't hurt either. @BClark09 wdyt?

**Comment by ThomDietrich** [comment] 2018-03-30 11:42
Guys, here is the new image: https://drive.google.com/open?id=1CF5RDQodnySwD57NdNeyJv6TWH5TRf5Z

Let me know how it performs and if there are relevant changes...

The image is based on `2018-03-13-raspbian-stretch-lite.zip` (latest), besides that almost nothing changed image-wise compared to the v1.4 image. This image is probably only useful for new setups, especially on a RPi3B+. No need to do a reinstall with it if your current system is fine. If you install this image you'll profit from latest changes to the raspbian base system. Both openHABian image versions would pull and install the latest openHABian configuration steps.

**Comment by mues-lee** [comment] 2018-03-30 12:34
@ThomDietrich 
> The "in case" here is imho not a realistic scenario but it wouldn't hurt either. 

well the not realistic "in case" scenario just happens and leads to a failed installation at the git installation

before apt upgrade:
`openhabian@openHABianPi:~$ sudo cat /etc/apt/sources.list
deb http://mirrordirector.raspbian.org/raspbian/ stretch main contrib non-free rpi`

after apt upgrade
`openhabian@openHABianPi:~$ sudo cat /etc/apt/sources.list
deb http://raspbian.raspberrypi.org/raspbian/ stretch main contrib non-free rpi`

here is the installation log, after a reboot (and with that a additional apt update) it works

2018-03-30_12:18:33_UTC [openHABian] Updating repositories and upgrading installed packages... OK
2018-03-30_12:23:21_UTC [openHABian] Installing git package... FAILED
2018-03-30_12:23:22_UTC [openHABian] Initial setup exiting with an error!


2018-03-30_12:28:42_UTC [openHABian] Starting the openHABian initial setup.
2018-03-30_12:28:42_UTC [openHABian] Storing configuration... OK
2018-03-30_12:28:43_UTC [openHABian] Changing default username and password... SKIPPED
2018-03-30_12:28:43_UTC [openHABian] Setting up Ethernet connection... OK
2018-03-30_12:28:43_UTC [openHABian] Ensuring network connectivity... OK
2018-03-30_12:28:46_UTC [openHABian] Waiting for dpkg/apt to get ready... OK
2018-03-30_12:29:17_UTC [openHABian] Updating repositories and upgrading installed packages... OK
2018-03-30_12:29:32_UTC [openHABian] Installing git package... OK
2018-03-30_12:30:26_UTC [openHABian] Cloning myself... OK`

**Comment by EliasGabrielsson** [comment] 2018-03-30 13:15
@ThomDietrich I have not identify any needs myself for the `first-boot.sh`. This issue (https://github.com/openhab/openhabian/issues/299) with wifi in power save have a solution which points to `rc.local`. I guess this is a good time to edit that file as well if needed. I can't advise on if this is needed or not, does not have a board with wifi.

**Comment by ThomDietrich** [comment] 2018-03-30 13:19
I was still unsure if we wanted to add this step as a default. I reluctant to second-guess decisions made for raspbian by a big group of experienced developers...
If we want to add that change, it would imho be something we can handle in one of the setup steps, no need to modify the image.

Btw: https://github.com/openhab/openhabian/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Image+v1.5

**Comment by mues-lee** [comment] 2018-03-30 15:38
@ThomDietrich 
just have created a PR, it fixes the git installation caused by repository change

**Comment by BClark09** [comment] 2018-03-31 18:02
Hey all! The image provided fails until @mues-lee's suggested (and now merged) change is included. After this, openhabian continues to work very well on a 3b+ and the newer bluetooth module works with the binding.

**Comment by ThomDietrich** [comment] 2018-04-01 12:33
Totally comes as a surprise to me. I thought the latest build of raspbian would contain a sane set of repositories. Thanks for fixing this @mues-lee !!

Are we ready to build (latest master) and release the RPi image v1.5 ?

**Comment by ThomDietrich** [comment] 2018-04-03 18:04
Hey guys, I'm about to upload the new image. I decided to go with "v1.4.1" because, honestly, not much changed since the previous image and I don't want to rattle existing v1.4 users.

https://github.com/openhab/openhabian/compare/v1.4...master

**Comment by ThomDietrich** [comment] 2018-04-03 18:26
https://community.openhab.org/t/openhabian-v1-4-released/37398

**Comment by EliasGabrielsson** [comment] 2018-04-03 20:16
Good choice, this is definitely a maintenance release. I would almost say that it is now tagged 1.5 is sort of maintenance issues as well but the scope can grove of course.

**Comment by ThomDietrich** [comment] 2018-04-04 16:08
Hey guys, the image is now online and seeing first downloads.

I want to thank you all for the help with this update. A special thanks goes to @philipb232 for reporting the issue and providing first hints towards the fix. Also to @mues-lee for engaging in the openHABian project. Lastly @EliasGabrielsson who as the new member of the Collaborators team for the project.

Keep up the great work guys ;)

**Closed by ThomDietrich** 2018-04-04 16:08 UTC
Labels: base system, bug
