### ISSUE TITLE
[docs/openhabian.md]Add Frontail description

### ISSUE THREAD

**Issue by Confectrician** [openhab/openhabian#391] opened 2018-05-02 07:59 UTC
For Reference:
openhab/openhab-docs#597 and 
openhab/openhab-docs#671

So in short:
We should add Frontail to the docs article and link the section to the docs logging article.
This way we can keep all explanation up to date with openhabian with out the need to change it somewhere else again.

I wanted to transfer my closed PR but it isn't that simple.

The Article is already really long and i haven't found a good place yet.
Also we should maybe ask the question, if frontail is the only optional component to provide an explanation for.

So feel free to discuss whats the best.

**Comment by ThomDietrich** [comment] 2018-05-15 14:48
Hey @Confectrician, thanks for following up. I'm also unsure about next steps. We could introduce subsections for all optional components... However where does it stop!? We can't start to explain all of them. That would widely exceed the scope of the article :-/

The problem is that the list behind https://docs.openhab.org/installation/openhabian.html#optional-components is not good for more detailed information. Maybe we should transform it into a multi-level list or a section with subheadlines per component. Wdyt?

**Comment by mstormi** [comment] 2020-03-26 16:06
Is this still an unresolved question ? If no please close.

**Comment by Confectrician** [comment] 2020-03-28 18:00
No changes from my side so far.

Feel free to close, when you think that the optional components are presented fine currently.

**Comment by mstormi** [comment] 2020-03-29 21:28
We have reworked the whole page, frontail is visibly presented and so are the other components.
Thomas' link is not leading anywhere any more, even the section he referred to no longer exists.
So I think it's ok to close this.

**Closed by mstormi** 2020-03-29 21:28 UTC
Labels: documentation
