### ISSUE TITLE
backup w/ amanda: S3 not selected, but script tries to setup

### ISSUE THREAD

**Issue by chris400** [openhab/openhabian#615] opened 2019-08-03 10:23 UTC
I am setting up a new openhabian instance on a raspberry pi3. It's debian 9.

I wanted to setup backup with amanda via openhabian-config. I select local storage, the question, if I want to backup to S3 does not come. But later in the menus I am asked for S3 webadresse, bucket and so on.

System ist up to date.

pls help me.

**Comment by mstormi** [comment] 2019-08-03 16:29
Can't reproduce. There always is a window to ask for S3 backup after local storage was configured, no matter if you choose local storage or not. Then it asks for S3 parameters.

**Comment by chris400** [comment] 2019-08-04 09:56
thx for the fast reply.

I never get asked, if I want to use AWS S3. I did two small recordings, which you find attached.

[recordings.zip](https://github.com/openhab/openhabian/files/3464783/recordings.zip)

**Comment by mstormi** [comment] 2019-08-04 10:03
Are you trying to fool me or didn't you read the window contents @0:40/0:30 ?

**Comment by chris400** [comment] 2019-08-04 11:37
sorry, I guess we have a misunderstanding, maybe my English is to bad or I'm to exhausted. I am totally not trying to fool you and will never do! 
I try to explain my approach with other words:

I want to setup backup w/ amanda to my local storage / NAS. I do _not_ want to use AWS S3, but the dialog keeps asking my for parameters for S3.

**Comment by mstormi** [comment] 2019-08-04 12:10
You *did* setup for local/NAS storage in your video 1. Where's your problem?

**Comment by chris400** [comment] 2019-08-04 12:22
my problem is, that it also creates a amanda-config for AWS. I am afraid that the setup is not completed or will cause failures in the future.

> [14:20:30] openhabian@openHABianPi:/etc/amanda$ ls
openhab-AWS  openhab-dir

**Comment by mstormi** [comment] 2019-08-04 12:24
You don't have to worry about that. If it makes you feel safer, remove the openhab-AWS directory.

**Comment by mstormi** [comment] 2019-08-04 21:11
Can you close the issue ?

**Closed** 2019-08-04 21:28 UTC
