### ISSUE TITLE
Install fails in firewalled environment

### ISSUE THREAD

**Issue by holgerfriedrich** [openhab/openhabian#594] opened 2019-07-07 06:46 UTC
I have experienced some trouble (installer does not proceed) when running a first time install in a firewalled environment.
Root cause seems to be that setting the system time fails.

Rpi does not have an RTC, thus starts up with a default system time (esp. on a clean install, where the last known system time cannot be restored from disk).
Both apt update and git checkout require at least a roughly matching system time, otherwise they will complain about invalid certificates. This is hidden by the way we call git/apt in the installer, so users don't have any idea what is going on.

This should be resolved in #579.

**Comment by mstormi** [comment] 2019-07-12 16:02
An environment to block NTP isn't matching the prerequisites for an openHABian install (which will also fail e.g. if there's no DHCP or DNS resolver), so I wouldn't call this an openHABian issue and rather suggest to close this.

**Comment by holgerfriedrich** [comment] 2019-07-14 12:38
A possible workaround for the installer script would be to get time via http, using the server time retrieved by a wget request. But maybe this is not a good approach at all, since it leaves openhabian install w/o working ntp.

A more general approach could be better: stop hiding errors from the end user. There are several while loops in the script which completely drop output of the command called. It would be much easier to diagnose if we print at least the error messages (maybe after a few tries...)

What do you think?

**Comment by ThomDietrich** [comment] 2019-07-15 20:36
> stop hiding errors from the end user

I generally agree, with the emphasize on "after a few tries" though. If at all possible our scripts should handle issues for the user (e.g. in while loops) but present errors when the issue is unexpected. As we all know the distinction is quite difficult.
Another suggestion a while back was to not pipe output and errors to /dev/null but into a debugging file. If you would like to suggest a solution for that, be my guest!

Regarding NTP: sounds like an edge case to me. In which environment did you encounter it?

**Comment by EliasGabrielsson** [comment] 2019-07-22 17:24
Could you elaborate on `firewalled environment"?
This sounds like an edge-case which should be "fixed" by defining prerequisite in the documentation.

**Comment by holgerfriedrich** [comment] 2019-07-23 08:54
Intranet setup, local NTP service, other NTP servers blocked normal PCs.
Let me check what happens if I configure ntp-servers correctly in my DHCP.
But agreed, seems to be an edge case and something to the documentation.

**Comment by holgerfriedrich** [comment] 2019-07-31 22:53
I had a closer look at this.
Setup is as described above: no access to NTP servers outside of the intranet, internal NTP server announced via DHCP. 
By looking at the DHCP traffic using dhcpdump I could verify that my server correctly announces ntp-servers as configured if requested by the client. But...

First, Raspbian dhcpcd does not use the ntp-servers request option by default (commented out in dhcpcd.conf).
Second, Raspbian uses systemd-timesyncd (which is a bit more lightweight compared to ntpd and does the syncing to disk which is useful for the RPI). dhcpcd has a hook only for ntpd.
Adding a hook file to dhcpcd is required, which creates /run/systemd/timesyncd.conf.d/dhcp-ntp.conf:
```
[Time]
NTP=...
```
See [this post](https://www.raspberrypi.org/forums/viewtopic.php?t=217832)

Having both implemented, it works fine for me. But I have the feeling that this is too much of an edge case and should not be added here.

So I would go on to add a prerequisite to the documentation that access to public NTP servers is required and give a link to this for more information. Agreed?

**Comment by EliasGabrielsson** [comment] 2019-08-01 08:33
Hi @holgerfriedrich. What a find, devils in the detail. 😃 

I don't mind adding this fix to the codebase as a lot of users are on RPi.
Eg. easier to maintain codebase then documentation.

I wonder if this fix could be applied when "building" the RPi image, i.e. adding that line to the filesystem?

**Comment by syoma755** [comment] 2019-08-08 19:10
Hi just, my comment. If git really required to run openhabian, why it is not included into openhabian distribution? If not - why don't install it later? 
I just ran into same issue, and think this is really making openhabian opposite to "hassle-free". Such troubles can not remain unresolvable.

**Comment by EliasGabrielsson** [comment] 2019-08-08 21:59
Hi @syoma755!
Sorry to hear that you got trouble. `git` shall be installed (included) during initial installation of openHABian on first boot. Did your system not install git?

The issue with syncing "NTP" to systemd-timesyncd will be fixed in future image.

**Comment by mstormi** [comment] 2019-12-25 18:40
@holgerfriedrich did buster change this behavior ?

**Comment by mstormi** [comment] 2020-03-26 15:53
@holgerfriedrich ping ... did the move to buster help ?

**Comment by mstormi** [comment] 2020-04-16 10:33
@holgerfriedrich another ping

**Comment by mstormi** [comment] 2020-04-20 11:40
@holgerfriedrich ping, pong, ping ...

.... would like to get this off the list (last slated for buster milestone where I don't think it belongs)

**Comment by holgerfriedrich** [comment] 2020-04-20 16:58
@mstormi not much time these days, let's keep his with low prio....

**Comment by mstormi** [comment] 2020-04-20 21:41
ok but I'll remove it from the buster milestone then (that image is out anyway :))

**Comment by mstormi** [comment] 2020-06-16 13:51
@holgerfriedrich could you please re-test if this is still an issue with the beta Raspi OS based image and current openHABian ?

**Comment by mstormi** [comment] 2020-06-17 19:32
@holgerfriedrich could you please re-test if this is still an issue with current openHABian master to contain the offline fixes ? I was able to install with Inet blocked.

**Comment by mstormi** [comment] 2020-06-24 10:25
@holgerfriedrich with offline install capability in the works anyway, we'll take care of this issue (sorta generalized version of your use case).
Will open another issue to fix NTP, though.

**Closed by mstormi** 2020-06-24 10:25 UTC
Labels: Network-related, bug
