### ISSUE TITLE
Node-RED install error

### ISSUE THREAD

**Issue by Wolfmanxxx** [openhab/openhabian#247] opened 2017-12-01 06:48 UTC
Hi,
i tied to install node-RED as rule engin but just get an error
"There was an error or interruption during the execution of: 20 | Optional Components"
I cant find any reference/issue of this on the web och here on GitHub..
Is there a solution i have not yet read?

**Comment by schoettik** [comment] 2017-12-01 10:16
I still have the same error ...

**Comment by dmitrymoshalkov** [comment] 2017-12-03 08:55
Confirm the same issue...

**Comment by ThomDietrich** [comment] 2017-12-03 14:59
Hey guys,
this is indeed a fresh bug and a simple error of the latest big change. Please update and try again. Should be fixed now. 😉

**Comment by Wolfmanxxx** [comment] 2017-12-04 07:31
After doing an update and tying to install i get a new error.
Now it tells me
"You appear to be running on ARMv6 hardware". "Please use the 'linux-armv6l' binary tarballs..."
i am using a Pi Zero

**Comment by ThomDietrich** [comment] 2017-12-04 16:43
Jup that's not a bug, that's a feature.
https://en.wikipedia.org/wiki/Raspberry_Pi#Specifications

😃 Of course we want to support the Pi Zero and there is already an issue to solve this limitation: #209 Would you like to offer a pull request?

**Closed by ThomDietrich** 2017-12-04 16:43 UTC
