### ISSUE TITLE
replace motd to match OH2 or OH3

### ISSUE THREAD

**Issue by mstormi** [openhab/openhabian#1273] opened 2020-11-29 11:48 UTC
on login to the box

make sure to change motd when migrating OH2<->OH3

**Comment by ecdye** [comment] 2020-11-29 22:05
I think I already fixed this? Did you test?

**Comment by mstormi** [comment] 2020-11-29 22:54
I just tried on my test box with current master and no it's still the 2.5 banner.
I think you said it would get deployed on a fresh install, that I haven't tried, but I would expect this to also change when you
up/downgrade OH through the menu.

(just to be sure we don't misunderstand: this is on ssh login - not in Karaf console).

**Comment by ecdye** [comment] 2020-11-30 03:43
Yes, perhaps I never merged it, I'll look into it.

**Comment by ecdye** [comment] 2020-11-30 15:49
I see what happened, it is a merge conflict and was overwritten on the OH3 branch. I'm fixing it now.

**Comment by ecdye** [comment] 2020-11-30 16:52
Actually, I was wrong, the code is in place the problem is that the branch update occurs after the migration and it must because it forces a restart of the tool to load the changes. I will look into a workaround.

**Comment by mstormi** [comment] 2020-12-01 20:10
Ran a downgrade to OH2 and ended up with

+ echo 'The tool will now restart to load the updates... OK'
The tool will now restart to load the updates... OK
+ exec '/opt/openhabian/openhabian-setup.sh migration'
/opt/openhabian/functions/openhabian.bash: line 183: /opt/openhabian/openhabian-setup.sh migration: No such file or directory
[21:08:21] root@openHABianDevice:/home/openhabian# ls -l /opt/openhabian/openhabian-setup.sh
-rwxr-xr-x 1 root root 3258 Dec  1 21:08 /opt/openhabian/openhabian-setup.sh
[21:08:45] root@openHABianDevice:/home/openhabian#

**Comment by mstormi** [comment] 2020-12-01 21:14
it was bad quotes, I fixed it

**Comment by mstormi** [comment] 2020-12-04 19:29
I got this on a fresh install (which has openhab2 installed by default)


sed: /var/lib/openhab/etc/version.properties kann nicht gelesen werden: Datei od                                                  er Verzeichnis nicht gefunden
sed: /var/lib/openhab/etc/version.properties kann nicht gelesen werden: Datei od                                                  er Verzeichnis nicht gefunden

                          _   _     _     ____   _
  ___   ___   ___   ___  | | | |   / \   | __ ) (_)  ____   ___
 / _ \ / _ \ / _ \ / _ \ | |_| |  / _ \  |  _ \ | | / _  \ / _ \
| (_) | (_) |  __/| | | ||  _  | / ___ \ | |_) )| || (_) || | | |
 \___/|  __/ \___/|_| |_||_| |_|/_/   \_\|____/ |_| \__|_||_| | |
      |_|                           -

**Comment by mstormi** [comment] 2020-12-06 00:03
the thing is we need to change /home/openhabian/.bash_profile, too

**Comment by ecdye** [comment] 2020-12-06 19:24
> the thing is we need to change /home/openhabian/.bash_profile, too.

Yes that should be taken care of already. It is most likely caused by the branch switching, that it is not taken care of on first install. I don't think it is really necessary to do much more than we have already as OH3 will enter stable soon and it wont matter.

FWIW I think we should just change the logo for all installations now in the code and let it stay the same until the user updates to a new OHian version. That way we save ourselves a lot of work and issues.

**Comment by mstormi** [comment] 2020-12-06 21:45
Isn't all that's left to replace the inline picture with the external one you keep installing on up & downgrade or am I mistaken?
Now if I'm wrong and it's way more difficult then we should proceed as you suggested but if it's just a bit more work then let's keep version dependent logos. I like the idea of instant recognition which version is installed thanks to the logo.

**Comment by ecdye** [comment] 2020-12-07 03:15
Yes, that should be fixing it properly already, right?

**Comment by mstormi** [comment] 2020-12-08 22:39
no as `.bash_profile` ain't replaced on OH up/downgrades.
So inline image out and cat `/path/to/image/that/i/dont/know/image.txt` in.

**Comment by ecdye** [comment] 2020-12-09 21:17
It should not be necessary as it should be switched with the branch, right? on OH3 branch it will update to OH3 logo, on OH2 branch it will update to OH2 logo. Manual installations are not supported and ore the only case where this would not be switched.

**Comment by mstormi** [comment] 2020-12-09 23:57
No .bash_profile does not get replaced on OH up- or downgrades.
So the user will have the inline image forever that is current at the time of image install (when .bash_profile gets created/copied).
That'll remain even when he upgrades and changes branch.
Do we talk about different things?

**Comment by ecdye** [comment] 2020-12-10 02:25
The Image is in .bash_profile which because of the branch migration I have set to copy over after each upgrade currently. Look at the code.

**Comment by mstormi** [comment] 2020-12-10 12:15
>  have set to copy over after each upgrade currently. Look at the code.

I don't see it. Granted need some more coffee but I think it's in bashrc_copy() which is only called via menu 1X or during unattended install. or?

**Comment by ecdye** [comment] 2020-12-10 16:02
Yes, but I changed that temporarily during our transition phase to keep it up to date.

**Comment by mstormi** [comment] 2020-12-11 23:59
well then

If you find the time please install another test system and up/downgrade it. It kept failing in my attempts but I don't know what to make of it yet.

**Comment by mstormi** [comment] 2020-12-22 22:20
I'm not the only one.
https://community.openhab.org/t/migration-from-oh2-5-to-oh3/110769

Could you please fix this once and for all ? I still think the image should not be inline in .bash_profile but that should be changed to print some filename. We could source /opt/openhabian/functions/openhab.bash and use is_openhab3_installed() to determine which pic to print.

**Comment by ecdye** [comment] 2020-12-23 17:05
Perhaps, but at this point, is it really necessary? OH3 is here and stable.

**Comment by mstormi** [comment] 2020-12-23 23:57
> Perhaps, but at this point, is it really necessary? OH3 is here and stable.

Yes please. Only a small fraction of users has migrated so far, many play around, some migrate forth and back, many more to follow up in the next days
It's really confusing whenever the banner does not match the software version so pretty please change it.

**Comment by ecdye** [comment] 2020-12-24 20:10
When I have time after the holiday, I will work on a fix.

**Closed** 2021-01-08 16:23 UTC
