### ISSUE TITLE
[OH3] Frontail no longer displays after new installation

### ISSUE THREAD

**Issue by dimmenhau** [openhab/openhabian#1383] opened 2021-01-05 15:57 UTC
## Issue information:
I have the problem that Frontail no longer displays on my Raspberry either. I also just reinstalled OH3 on the server and the problem is there too.

I also get the following message in the DevTool of Chrome:
    
    index.js:83 WebSocket connection to 'ws://192.168.0.51:9001/socket.io/?EIO=3&transport=websocket' failed: Error during WebSocket handshake: Unexpected response code: 400
    
## Logfile from openhabian-config
[openhabian.log](https://github.com/openhab/openhabian/files/5771216/openhabian.log)

## System information:
    Branch: OH3
    
    openhabian@openhab:~$ cat /proc/cpuinfo | grep Model
    Model		: Raspberry Pi 4 Model B Rev 1.2
    
    openhabian@openhab:~$ cat /etc/os-release
    PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
    NAME="Raspbian GNU/Linux"
    VERSION_ID="10"
    VERSION="10 (buster)"
    VERSION_CODENAME=buster
    ID=raspbian
    ID_LIKE=debian
    HOME_URL="http://www.raspbian.org/"
    SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
    BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
    openhabian@openhab:~$ uname -m
    armv7l

**Comment by mstormi** [comment] 2021-01-05 21:08
I never used frontail and have no idea why so cannot help.
The spawned processes by themselves work fine so permissions etc are correct.

**Comment by JDog1895** [comment] 2021-01-06 07:17
I've got this problem too. 

In the frontail.service the start-parameter is this:

`ExecStart=/usr/lib/node_modules/frontail/bin/frontail --ui-highlight --ui-highlight-preset /usr/lib/node_modules/frontail/preset/openhab.json -t openhab -l 2000 -n 200 /var/log/openhab2/openhab.log /var/log/openhab2/events.log`

I tried to rename the path from openhab2 to openhab and restart the service,but no luck.

**Comment by juanhaywood** [comment] 2021-01-06 08:35
+1 for this issue, and same error in the browser console. Happy to do tests if someone has any suggestions.

**Comment by bwiessneth** [comment] 2021-01-06 13:03
Also happening for me. I don't know what triggered this behavior.

But I found more of a workaround than a fix (introducing a performance trade-off).
Edit **/usr/lib/node_modules/frontail/web/index.html** and replace ``websocket`` with ``polling``

From this 

        var socket = new io.connect('/__NAMESPACE__', {
            path: '__PATH__/socket.io',
            transports: ['websocket']
        });

to this

        var socket = new io.connect('/__NAMESPACE__', {
            path: '__PATH__/socket.io',
            transports: ['websocket']
        });

**Comment by florian-h05** [comment] 2021-01-06 14:15
I have the same issue with my frontail installation, the same error in the console log.

To me it seems, that this problem is only with _frontail Version 4.9.1_
**I downgraded to _frontail Version 4.9.0_ and the issue was solved.**

This is just a workaround, but it seems that the problem is in frontail and not in openhabian.

**Comment by florian-h05** [comment] 2021-01-06 14:19
> I have the same issue with my frontail installation, the same error in the console log.
> 
> To me it seems, that this problem is only with _frontail Version 4.9.1_
> **I downgraded to _frontail Version 4.9.0_ and the issue was solved.**
> 
> This is just a workaround, but it seems that the problem is in frontail and not in openhabian.

I am going to try to make frontail downgrade over openhabian-config

**Comment by RogerG007** [comment] 2021-01-06 14:28
One of the differences between frontail v4.9.1 and frontail v4.9.0 is that in **/usr/lib/node_modules/frontail/web/index.html**
`transports: ['websocket']` wasn't in the previous version. So I assume it will also fallback to 'polling' as with the proposed workaround. 

As frontail v4.9.1 has been already available since March 2020 and working, I'm not sure if the problem is to be blamed on frontail.

**Comment by florian-h05** [comment] 2021-01-06 14:35
@RogerG007 

So what should we do now?
Downgrading to _frontail 4.9.0_ as a fast & easy workaround? So that frontail is running correctly and there is time to make _frontail 4.9.1_ running?

**Comment by RogerG007** [comment] 2021-01-06 15:44
Apologies, didn't want to stop you there. A fast & easy solution is probably the best and no one has found the real cause, yet.

**Comment by ecdye** [comment] 2021-01-06 16:26
Has anyone attempted reinstalling frontail using `openhabian-config` menu option 21. I have used it successfully on OH3 several times while testing in recent days.

**Comment by RogerG007** [comment] 2021-01-06 16:35
Yes, this is something I've tried but it didn't help. It (re-)installs the log viewer successfully and without any faults but the above behaviour persists.

**Comment by WolfgangSn** [comment] 2021-01-06 16:45
* I do not have the problem on Debian Buster 10 , x86
* as frontail itself was not changed since about 9 months the root cause should be something else I would conclude
* what else changes were done ? 
   e.g. what else packages were recently updated ( ls -lt /var/lib/dpkg/info/*.list |more ) on my system I see that nodejs was updated
* what about the related / required nodejs library packages ?

**Comment by bwiessneth** [comment] 2021-01-06 16:54
Seems like an issue with socket.io (which frontail utilizes for websocket transport). See https://github.com/socketio/socket.io/issues/3740

**Comment by WolfgangSn** [comment] 2021-01-06 18:06
> Seems like an issue with socket.io (which frontail utilizes for websocket transport). See [socketio/socket.io#3740](https://github.com/socketio/socket.io/issues/3740)

I checked which version of socket.io is used in my installation. It is 2.3.0.
This would explain why it works in my environment as the ticket about socket.io states that the problem was introduced with version 2.4.0.

**Comment by juanhaywood** [comment] 2021-01-06 18:08
> * I do not have the problem on Debian Buster 10 , x86

Very odd. I'm having this behavior on Debian Buster 10 x86, after doing a clean install.

**Comment by WolfgangSn** [comment] 2021-01-06 18:10
> > * I do not have the problem on Debian Buster 10 , x86
> 
> Very odd. I'm having this behavior on Debian Buster 10 x86, after doing a clean install.
Please check which socket.io version you have.

**Comment by ecdye** [comment] 2021-01-06 19:04
As this is an upstream issue, I am going to close this for now. Please reopen if anything changes.

**Closed by ecdye** 2021-01-06 19:04 UTC

**Comment by juanhaywood** [comment] 2021-01-08 16:55
The breaking change was reverted with socket.io 2.4.1 (https://github.com/socketio/socket.io/releases/tag/2.4.1). I've just tested with a clean install of Debian, running `openhabian-config unattended`. Frontail working as expected now.
