### ISSUE TITLE
openHabian Configuration tool "Manual/Fresh Setup" V 1.4-376 can not select options

### ISSUE THREAD

**Issue by borrismountain** [openhab/openhabian#345] opened 2018-03-07 18:39 UTC
sudo openhabian-config brings up the openHabian Configuration tool correctly and you can select any options in this menu ok. But when you select 60 Manual/Fresh Setup the next menu opens but you can not select any of the items to install, it is if all the menu items have been disabled. the only two options are
<execute. and <back>
The previous version worked correctly as this is the method I installed all of the packages fro Manual/Fresh Setup

**Comment by nesys** [comment] 2018-03-16 17:41
same issue here ... 1.4-377(f5061f6)

**Comment by nesys** [comment] 2018-03-16 17:48
just found a workaround ... it seems the issue is related to the window of the screen. Try connecting via ssh and expand the window of your terminal as appropriate. That fixed the issue for me.

**Comment by ThomDietrich** [comment] 2018-03-17 12:41
I can't reproduce the issue but if the last comment by @nesys solves it then the actual problem is, that you are using your system with a connected display, which is just not meaningful. See: http://docs.openhab.org/installation/openhabian.html#headache

**Comment by nesys** [comment] 2018-03-17 13:25
Thom, this can happen with a bad display ... that means also, like me, via ssh, if your debian is hosted in a virtual machine.

**Comment by ThomDietrich** [comment] 2018-03-18 16:38
Okay... what is the actual issue? Could you post a screenshot or photo?

**Comment by borrismountain** [comment] 2018-03-18 19:19
![capture1](https://user-images.githubusercontent.com/33997422/37569915-4f9b0946-2b3d-11e8-97cd-e65e3f74cd06.GIF)
![capture2](https://user-images.githubusercontent.com/33997422/37569916-4fd1f4ba-2b3d-11e8-9fac-6b3579562a94.GIF)
![capture3](https://user-images.githubusercontent.com/33997422/37569917-5003c404-2b3d-11e8-9492-c358a4e7d98d.GIF)
![capture4](https://user-images.githubusercontent.com/33997422/37569919-5039fd62-2b3d-11e8-866f-7e584bff935d.GIF)

**Comment by borrismountain** [comment] 2018-03-18 19:25
I have attaced screen shots as requested. I Changed screen width in SSH Client to 115 and resolved issue, however the default setting in 100 in SSH Client, ( I haven't had to change this before) The 1st Menu Screen works , It seems changes were made to the Manual setup menu i.e. got bigger....previous versions of this tool had no problems....

**Comment by ThomDietrich** [comment] 2018-03-19 10:49
I see. @EliasGabrielsson 

Well this was a rather important change by @EliasGabrielsson. https://github.com/openhab/openhabian/pull/331
I had issues like this one in the past, most often it got resolved by reducing the length of the longest description (FireMotD in this case). @EliasGabrielsson could you have a look?

**Comment by EliasGabrielsson** [comment] 2018-03-19 12:08
I manage to reproduce the error you described above as well. 
An easy "fix" would be to check if the terminal is less then 120 columns with `tput cols` on startup and otherwise recommend the user to change the width.

**Comment by borrismountain** [comment] 2018-03-20 05:03
Thankyou for the input to the issue. As a beginner to openhab all process have been seamless in operation everything installing as it should great system and easy to follow and understand installation documentation etc... The default settings of the SSH client screen width is 100 when I installed Bitvise SSH client, (Would not think of changing width as 1st screen was ok). Also not sure how to use the tput cols on start up. Have now set col width to 120 in SSH client all is good....If the Author could make a change or add in the installation documentation to set col width in their SSH client to 120 would be great for new users

**Comment by ThomDietrich** [comment] 2018-03-20 16:21
Hmmm another example would be putty, which defaults to 80 columns. Imho we can't adjust the menu to work with 80/100 columns without drastically reducing the descriptions, which in return would lower the usefulness of the whole tool.
@EliasGabrielsson I like your suggestion. This could be one of the preliminary steps, just as  https://github.com/openhab/openhabian/blob/master/functions/openhabian.sh#L12

**Closed** 2018-04-01 12:28 UTC
Labels: base system, documentation

**Comment by ThomDietrich** [comment] 2018-04-01 12:36
Hey guys! The discussed change was added by @EliasGabrielsson. After updating the configuration tool you should see a warning if your console is too small. Please test and let us know if something doesn't work or is misleading ;)

Happy Easter!
