### ISSUE TITLE
first-boot.bash fails to install can't-be-wrong packages 

### ISSUE THREAD

**Issue by zobelhelas** [openhab/openhabian#644] opened 2019-08-06 15:34 UTC
```
2019-08-06_16:22:05_BST [openHABian] Installing basic can't-be-wrong packages (screen, vim, ...)... 
$ apt-get update 
Hit:1 http://raspbian.raspberrypi.org/raspbian buster InRelease
Hit:2 http://archive.raspberrypi.org/debian buster InRelease
Reading package lists...

$ apt-get -y install screen vim nano mc vfu bash-completion htop curl wget multitail git bzip2 zip unzip xz-utils software-properties-common man-db whiptail acl usbutils dirmngr arping 
Reading package lists...
Building dependency tree...
Reading state information...
Package screen is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package zip is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package vim is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'screen' has no installation candidate
E: Package 'vim' has no installation candidate
E: Unable to locate package vfu
E: Package 'zip' has no installation candidate
E: Unable to locate package software-properties-common
FAILED
+ fail_inprogress
+ rm -f /opt/openHABian-install-inprogress
+ touch /opt/openHABian-install-failed
++ timestamp
++ date +%F_%T_%Z
+ echo -e '2019-08-06_16:22:13_BST [openHABian] Initial setup exiting with an error!\n\n'
2019-08-06_16:22:13_BST [openHABian] Initial setup exiting with an error!


+ exit 1
root@openhab:~# apt update
Hit:1 http://raspbian.raspberrypi.org/raspbian buster InRelease
Hit:2 http://archive.raspberrypi.org/debian buster InRelease
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
root@openhab:~# apt-get -y install screen vim nano mc vfu bash-completion htop curl wget multitail git bzip2 zip unzip xz-utils software-properties-common man-db whiptail acl usbutils dirmngr arping
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package screen is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package zip is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package vim is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'screen' has no installation candidate
E: Package 'vim' has no installation candidate
E: Unable to locate package vfu
E: Package 'zip' has no installation candidate
E: Unable to locate package software-properties-common
root@openhab:~# apt-cache policy screen
screen:
  Installed: (none)
  Candidate: (none)
  Version table:
root@openhab:~#
root@openhab:~# cd /etc/apt/
root@openhab:/etc/apt# cat sources.list
deb http://raspbian.raspberrypi.org/raspbian/ buster main contrib non-free rpi
# Uncomment line below then 'apt-get update' to enable 'apt-get source'
#deb-src http://raspbian.raspberrypi.org/raspbian/ buster main contrib non-free rpi
root@openhab:/etc/apt# cat sources.list.d/raspi.list 
deb http://archive.raspberrypi.org/debian/ buster main
# Uncomment line below then 'apt-get update' to enable 'apt-get source'
#deb-src http://archive.raspberrypi.org/debian/ buster main
root@openhab:/etc/apt# cd /var/lib/apt/lists/
root@openhab:/var/lib/apt/lists# grep "Package: screen" *_Packages
root@openhab:/var/lib/apt/lists# grep "Package: vim" *_Packages
root@openhab:/var/lib/apt/lists# grep "Package: vfu" *_Packages
root@openhab:/var/lib/apt/lists# grep "Package: software-properties-common" *_Packages

```

**Comment by mstormi** [comment] 2019-08-06 18:01
What base OS / HW do you run on ?

**Comment by zobelhelas** [comment] 2019-08-06 18:09
openhabian based on Buster (downloaded from https://github.com/openhab/openhabian/releases/download/v1.5/openhabian-pi-raspbian-201908050414-gitca0976f-crc6a66b5a1.img.xz) on a Raspberry Pi 3.

**Comment by mstormi** [comment] 2019-08-06 21:39
I don't know what went wrong with your box but it is no general openhabian issue, you're the only one to report this. Maybe an issue with your Internet connection or the repo. I'd try starting over.

**Comment by zobelhelas** [comment] 2019-08-06 21:56
TBH, I doubt your conclusion. With my Debian Developer hat on, I do believe that apt does exactly what your or the raspbian archive offers for download. That is why i ran "apt-get update" as the first thing after the first-boot.bash script failed.

**Comment by mstormi** [comment] 2019-08-07 08:41
> I do believe that apt does exactly what your or the raspbian archive offers for download

If that was the case then everybody should be having this problem, right?
Either way, there is no information in your post that identifies a faulty part of openHABian or helps in finding the root cause of your problem, so we can't do anything about it.
So please either deliver that or close the issue, please.

**Comment by EliasGabrielsson** [comment] 2019-08-17 10:40
Hi @zobelhelas!
Thanks for reaching out and posting the log. Can't really wrap my head around the issue though.
Did you try to make another installation (from reflashed image), was it a success?

**Comment by kronoxnl** [comment] 2019-10-23 13:41
Hi, here the same problems. After a clean fresh download and new sd  card. Install failed. First-boot bash failed.

**Comment by mstormi** [comment] 2020-03-26 15:29
Haven't seen again since and cannot reproduce. Please open a new issue if you still have this problem.

**Closed by mstormi** 2020-03-26 15:29 UTC
