### ISSUE TITLE
During initial setup: "java_zulu_embedded: command not found"

### ISSUE THREAD

**Issue by bonieP** [openhab/openhabian#508] opened 2019-01-10 21:11 UTC
The initial setup was not able to finish successfully.
There seems to be an issue with the zulu jre.
Here is the output of ```cat /boot/first-boot.log```:
```[21:57:16] openhabian@openHABianPi:~$ cat /boot/first-boot.log
2018-03-13_22:53:58_UTC [openHABian] Starting the openHABian initial setup.
2018-03-13_22:53:58_UTC [openHABian] Storing configuration... OK
2018-03-13_22:53:58_UTC [openHABian] Changing default username and password... OK
2018-03-13_22:54:00_UTC [openHABian] Setting up Wi-Fi connection... OK, rebooting...
2018-03-13_22:54:11_UTC [openHABian] Starting the openHABian initial setup.
2018-03-13_22:54:11_UTC [openHABian] Storing configuration... OK
2018-03-13_22:54:11_UTC [openHABian] Changing default username and password... SKIPPED
2018-03-13_22:54:11_UTC [openHABian] Setting up Wi-Fi connection... OK
2018-03-13_22:54:11_UTC [openHABian] Ensuring network connectivity... OK
2018-03-13_22:54:11_UTC [openHABian] Waiting for dpkg/apt to get ready... OK
2019-01-10_19:24:19_UTC [openHABian] Updating repositories and upgrading installed packages... OK
2019-01-10_19:33:57_UTC [openHABian] Installing git package... OK
2019-01-10_19:34:50_UTC [openHABian] Cloning myself... OK
2019-01-10_19:34:52_UTC [openHABian] Executing 'openhabian-setup.sh unattended'...
2019-01-10_19:34:53_UTC [openHABian] Checking for root privileges... OK
2019-01-10_19:34:53_UTC [openHABian] Loading configuration file '/etc/openhabian.conf'... OK
2019-01-10_19:34:53_UTC [openHABian] Setting timezone based on IP geolocation... OK (Europe/Berlin)
2019-01-10_20:36:56_CET [openHABian] Setting locale based on openhabian.conf... OK
2019-01-10_20:37:23_CET [openHABian] Setting hostname of the base system... OK
2019-01-10_20:37:23_CET [openHABian] Setting the GPU memory split down to 16MB for headless system... OK
2019-01-10_20:37:23_CET [openHABian] Enabling Audio output... OK
2019-01-10_20:37:23_CET [openHABian] Installing basic can't-be-wrong packages (screen, vim, ...)... OK
2019-01-10_20:38:57_CET [openHABian] Installing additional needed packages... OK
2019-01-10_20:39:20_CET [openHABian] Installing additional bluetooth packages... OK
2019-01-10_20:39:36_CET [openHABian] Adding slightly tuned bash config files to system... OK
2019-01-10_20:39:36_CET [openHABian] Adding slightly tuned vim config file to system... OK
2019-01-10_20:39:36_CET [openHABian] Downloading and setting up FireMotD... OK
/opt/openhabian/openhabian-setup.sh: line 70: java_zulu_embedded: command not found
2019-01-10_20:40:20_CET [openHABian] Installing or upgrading to latest openHAB release (stable)... OK
2019-01-10_20:41:56_CET [openHABian] Adding an openHAB dashboard tile for 'openhabiandocs'... OK
2019-01-10_20:41:56_CET [openHABian] Adding openHAB syntax to vim editor... OK
2019-01-10_20:41:56_CET [openHABian] Adding openHAB syntax to nano editor... OK
2019-01-10_20:41:57_CET [openHABian] Adding openHAB scheme to multitail... OK
2019-01-10_20:41:57_CET [openHABian] Preparing openHAB folder mounts under /srv/... OK
2019-01-10_20:41:57_CET [openHABian] Applying file permissions recommendations... OK
2019-01-10_20:41:59_CET [openHABian] Applying miscellaneous system settings... OK
2019-01-10_20:41:59_CET [openHABian] Setting up Samba network shares... OK
2019-01-10_20:43:26_CET [openHABian] Installing Node.js for arm (prerequisite for other packages)... OK
2019-01-10_20:43:52_CET [openHABian] Installing the openHAB Log Viewer (frontail)... OK
2019-01-10_20:44:32_CET [openHABian] Adding an openHAB dashboard tile for 'frontail'... OK
2019-01-10_20:44:33_CET [openHABian] Execution of 'openhabian-setup.sh unattended' completed.
2019-01-10_20:44:33_CET [openHABian] Waiting for openHAB to become ready... 2019-01-10_21:07:02_CET [openHABian] Starting the openHABian initial setup.
2019-01-10_21:07:02_CET [openHABian] Storing configuration... OK
2019-01-10_21:07:02_CET [openHABian] Changing default username and password... SKIPPED
2019-01-10_21:07:02_CET [openHABian] Setting up Wi-Fi connection... OK
2019-01-10_21:07:02_CET [openHABian] Ensuring network connectivity... OK
2019-01-10_21:07:03_CET [openHABian] Waiting for dpkg/apt to get ready... OK
2019-01-10_21:07:12_CET [openHABian] Updating repositories and upgrading installed packages... OK
2019-01-10_21:07:34_CET [openHABian] Installing git package... OK
2019-01-10_21:07:48_CET [openHABian] Cloning myself... FAILED
2019-01-10_21:07:48_CET [openHABian] Initial setup exiting with an error!
```

**Comment by ThomDietrich** [comment] 2019-01-10 21:32
Hello @bonieP,
we are sorry about this bug, which was introduced just today (#459) I've resolved it just now and you should be able to run the openHABian installation now. Just flash the image again and I'm confident it will succeed. Enjoy!

**Comment by bonieP** [comment] 2019-01-10 22:15
Bad timing i guess ;-)
Thanks for the quick reply! Bad sadly it seems like there is still another issue:
```2018-03-13_22:53:58_UTC [openHABian] Starting the openHABian initial setup.
2018-03-13_22:53:58_UTC [openHABian] Storing configuration... OK
2018-03-13_22:53:58_UTC [openHABian] Changing default username and password... OK
2018-03-13_22:54:00_UTC [openHABian] Setting up Wi-Fi connection... OK, rebooting...
2018-03-13_22:54:12_UTC [openHABian] Starting the openHABian initial setup.
2018-03-13_22:54:12_UTC [openHABian] Storing configuration... OK
2018-03-13_22:54:12_UTC [openHABian] Changing default username and password... SKIPPED
2018-03-13_22:54:12_UTC [openHABian] Setting up Wi-Fi connection... OK
2018-03-13_22:54:12_UTC [openHABian] Ensuring network connectivity... OK
2018-03-13_22:54:12_UTC [openHABian] Waiting for dpkg/apt to get ready... OK
2019-01-10_21:44:46_UTC [openHABian] Updating repositories and upgrading installed packages... OK
2019-01-10_21:53:21_UTC [openHABian] Installing git package... OK
2019-01-10_21:54:15_UTC [openHABian] Cloning myself... OK
2019-01-10_21:54:21_UTC [openHABian] Executing 'openhabian-setup.sh unattended'...
2019-01-10_21:54:21_UTC [openHABian] Checking for root privileges... OK
2019-01-10_21:54:21_UTC [openHABian] Loading configuration file '/etc/openhabian.conf'... OK
2019-01-10_21:54:21_UTC [openHABian] Setting timezone based on IP geolocation... OK (Europe/Berlin)
2019-01-10_22:56:21_CET [openHABian] Setting locale based on openhabian.conf... OK
2019-01-10_22:56:55_CET [openHABian] Setting hostname of the base system... OK
2019-01-10_22:56:55_CET [openHABian] Setting the GPU memory split down to 16MB for headless system... OK
2019-01-10_22:56:55_CET [openHABian] Enabling Audio output... OK
2019-01-10_22:56:56_CET [openHABian] Installing basic can't-be-wrong packages (screen, vim, ...)... OK
2019-01-10_22:58:37_CET [openHABian] Installing additional needed packages... OK
2019-01-10_22:59:04_CET [openHABian] Installing additional bluetooth packages... OK
2019-01-10_22:59:16_CET [openHABian] Adding slightly tuned bash config files to system... OK
2019-01-10_22:59:16_CET [openHABian] Adding slightly tuned vim config file to system... OK
2019-01-10_22:59:16_CET [openHABian] Downloading and setting up FireMotD... OK
/opt/openhabian/includes/azul-zulu-license.md: No such file or directory
2019-01-10_23:02:23_CET [openHABian] Installing or upgrading to latest openHAB release (stable)... OK
2019-01-10_23:03:48_CET [openHABian] Adding an openHAB dashboard tile for 'openhabiandocs'... OK
2019-01-10_23:03:48_CET [openHABian] Adding openHAB syntax to vim editor... OK
2019-01-10_23:03:49_CET [openHABian] Adding openHAB syntax to nano editor... OK
2019-01-10_23:03:49_CET [openHABian] Adding openHAB scheme to multitail... OK
2019-01-10_23:03:49_CET [openHABian] Preparing openHAB folder mounts under /srv/... OK
2019-01-10_23:03:50_CET [openHABian] Applying file permissions recommendations... OK
2019-01-10_23:03:52_CET [openHABian] Applying miscellaneous system settings... OK
2019-01-10_23:03:52_CET [openHABian] Setting up Samba network shares... OK
2019-01-10_23:05:13_CET [openHABian] Installing Node.js for arm (prerequisite for other packages)... OK
2019-01-10_23:05:37_CET [openHABian] Installing the openHAB Log Viewer (frontail)... OK
2019-01-10_23:06:17_CET [openHABian] Adding an openHAB dashboard tile for 'frontail'... OK
2019-01-10_23:06:18_CET [openHABian] Execution of 'openhabian-setup.sh unattended' completed.
2019-01-10_23:06:18_CET [openHABian] Waiting for openHAB to become ready...
```

**Comment by ThomDietrich** [comment] 2019-01-11 09:36
@mstormi could you please have a look?

**Comment by mstormi** [comment] 2019-01-11 10:33
/opt/openhabian/includes/azul-zulu-license.md is in the current openhabian repo, isn't it ? So the reason isn't obvious to me.
Maybe the openhabian-config updater doesn't fetch that ? Or some mistake on the OP's part or just bad timing ?
Not sure.

**Comment by mstormi** [comment] 2019-01-11 12:36
Well spotted, thanks.
@ThomDietrich: PR#511

**Comment by ThomDietrich** [comment] 2019-01-11 14:30
Thanks Markus for fixing the issue
Thanks @bonieP and @elektronaut69 for spotting, reporting and investigating it 😃 We are sorry for the troubles you had but at least now you have the positive feeling you only get from helping in an open source community 👏 
Enjoy your openHABian system!

**Comment by mstormi** [comment] 2019-01-11 16:09
yes SW testing is a huge effort on its own.
I guess you get the messy output because the file is displayed although running in unattended mode, it shouldn't do that. But did the install succeed ?

**Comment by mstormi** [comment] 2019-01-11 16:16
next try https://github.com/openhab/openhabian/pull/512

**Comment by elektronaut69** [comment] 2019-01-11 16:30
I am affraid the install did not succeed. It stalls at `2019-01-11_17:15:58_CET [openHABian] Waiting for openHAB to become ready...`.
I checked the status of openhab2 on a different console:
```
sudo service openhab2 status
● openhab2.service - openHAB 2 - empowering the smart home
   Loaded: loaded (/usr/lib/systemd/system/openhab2.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Fri 2019-01-11 16:41:22 CET; 30ms ago
     Docs: https://www.openhab.org/docs/
           https://community.openhab.org
  Process: 3529 ExecStop=/usr/share/openhab2/runtime/bin/karaf stop (code=exited, status=1/FAILURE)
  Process: 3510 ExecStart=/usr/share/openhab2/runtime/bin/karaf $OPENHAB_STARTMODE (code=exited, status=1/FAILURE)
 Main PID: 3510 (code=exited, status=1/FAILURE)

Jan 11 16:41:22 openHABianPi systemd[1]: openhab2.service: Failed with result 'exit-code'.
```

**Comment by AllenSlaghuis** [comment] 2019-01-11 17:44
`[18:34:02] openhabian@openHABianPi:~$ sudo /boot/first-boot.sh
2019-01-11_18:35:02_SAST [openHABian] Starting the openHABian initial setup.
2019-01-11_18:35:02_SAST [openHABian] Storing configuration... OK
2019-01-11_18:35:02_SAST [openHABian] Changing default username and password... SKIPPED
2019-01-11_18:35:02_SAST [openHABian] Setting up Ethernet connection... OK
2019-01-11_18:35:02_SAST [openHABian] Ensuring network connectivity... OK
2019-01-11_18:35:02_SAST [openHABian] Waiting for dpkg/apt to get ready... OK
2019-01-11_18:35:10_SAST [openHABian] Updating repositories and upgrading installed packages... OK
2019-01-11_18:35:27_SAST [openHABian] Installing git package... OK
2019-01-11_18:35:37_SAST [openHABian] Cloning myself... FAILED
2019-01-11_18:35:37_SAST [openHABian] Initial setup exiting with an error!
`

**Comment by elektronaut69** [comment] 2019-01-11 17:51
Seems like there is something going wrong with the install of java_zulu_embedded. I did install openjdk9 manually and after that openhab does start and the webinterface is also accessible.

**Comment by zerofruchtshake** [comment] 2019-01-11 17:56
i get the same error as
https://github.com/openhab/openhabian/issues/508#issuecomment-453553851

**Comment by andreas-bulling** [comment] 2019-01-11 21:18
same here

**Comment by ThomDietrich** [comment] 2019-01-11 21:36
The PR was merged, this should now be resolved. 
@bonieP hope it's working now.
@elektronaut69 the mistake in the Zulu routine left your system without a java runtime. We should check for one during the openHAB setup. I'll create an issue for this.
@AllenSlaghuis you got stuck at a different problem. This is not a bug of openHABian but can for sure be improved upon. I've already created an issue for it.
@zerofruchtshake @andreas-bulling please try again!

**Comment by andreas-bulling** [comment] 2019-01-11 21:42
@ThomDietrich doesn't work I am afraid. zulu gets extracted to /opt/jdk/ but it seems the update-alternative command doesn't do what it's supposed to do. java binary not found in path, openhabian doesn't start as a result of that.

**Comment by ThomDietrich** [comment] 2019-01-11 21:56
@EliasGabrielsson do you agree that we should revert to the old repository based zulu routine for today? The new tar-based routine clearly needs some more testing.

**Comment by elektronaut69** [comment] 2019-01-11 22:02
@ThomDietrich <https://github.com/ThomDietrich> I reflashed after you did
change the jdk-routine. Seems like something goes seriously wrong when
installing the jdk as this error is breaking openhabian.

Am Fr., 11. Jan. 2019, 22:42 hat andreas-bulling <notifications@github.com>
geschrieben:

**Comment by bonieP** [comment] 2019-01-11 22:14
Yep can confirm, it is still not working

**Comment by zerofruchtshake** [comment] 2019-01-12 09:11
Now i get stuck at
`[openHABian] Waiting for dpkg/apt to get ready...`
left it running for nearly an hour and nothing happened

**Comment by DUNDERTRiX** [comment] 2019-01-12 11:15
After the revert of #459 it works for me.

**Comment by elektronaut69** [comment] 2019-01-12 12:50
For me too.

Am Sa., 12. Jan. 2019 um 12:15 Uhr schrieb DUNDERTRiX <
notifications@github.com>:

**Comment by ThomDietrich** [comment] 2019-01-13 20:50
Guys,
I need to apologize to everyone involved in this issue. As some might know I was occupied with personal stuff for most of 2018. I am slowly coming back to the open source community and found some time to look into openHABian. 
The merge of PR #459 was too reckless and a lack of oversight on my side. The PR touched an important part of the unattended installation and hence needed extra attention and thorough testing. In the past testing was mostly done manually but in response to this event we will look into the installation of an automated testing system as part of the continuous integration toolchain. If you want to learn more please see #520 

Thanks to everyone for their help and patience!

**Comment by mstormi** [comment] 2019-03-10 16:30
@ThomDietrich @EliasGabrielsson how do we want to proceed with this now ?
There's no progress on #520 AFAIK and for the time being we still deliver old Java, don't we?

Can you test if the current java_zulu_NEW() works for you ?

(BTW needs another update as Zulu Java now is at 8u202)

**Comment by EliasGabrielsson** [comment] 2019-03-10 16:42
I am indirectly working on this as we speak. I have managed to do a test-solution locally with docker and bats testing  amongs other the Java installation. I have not get it to work smoothly with travis yet, investigating that now. When that issue is cleared I will push a PR including the java update.

**Closed** 2019-03-20 09:55 UTC
Labels: base system, bug-regression
