### ISSUE TITLE
NodeJS on armv6l not working

### ISSUE THREAD

**Issue by Norde** [openhab/openhabian#1038] opened 2020-07-17 16:22 UTC
OS : openHABian 2.5.6 (Raspbian buster), fresh install
Package update : 17-07-2020
Hardware : Raspberry pi zeroW

Installation of NodeRED using openhabian-config or [update-nodejs-and-nodered](https://raw.githubusercontent.com/node-red/linux-installers/master/deb/update-nodejs-and-nodered) script fail.

This occur at stage "Install Node.js" :
```

  Stop Node-RED                            ✔
  Remove old version of Node-RED ✔
  Remove old version of Node.js       -
  Install Node.js  LTS                         ✘   Failed to install Node.js - Exit
  Clean npm cache
  Install Node-RED core
  Move global nodes to local
  Install extra Pi nodes
  Npm rebuild existing nodes
  Add shortcut commands
  Update systemd script
```

/var/log/nodered-install.log give no information :

```
Started : Thu 16 Jul 2020 05:58:19 PM CEST
Running for user openhabian at /home/openhabian
Failed to stop nodered.service: Unit nodered.service not loaded.
Found global nodes:   :

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
Package 'nodered' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 5 not upgraded.
Already have nodejs
Now install nodejs
Versions: node: npm:
```

Also preinstalled node and npm command fail with a "Illegal instruction".
It seems that the installed versions are not compatible with armv6l.

Removing these defective packages does not resolve the issue as they are reinstalled with the automated script.

The NodeRED automated installation works on fresh raspian install (using [update-nodejs-and-nodered](https://raw.githubusercontent.com/node-red/linux-installers/master/deb/update-nodejs-and-nodered) script) so it's specific to openhabian.

Something trigger the "Install Node.js LTS" condition instead of "Install Node.js for Armv6" of update-nodejs-and-nodered script.

**Comment by ecdye** [comment] 2020-07-17 17:08
Hmm, that's odd. I wonder what caused that. It might be fixed by #1002. You could try using the changes made in #1002 and see if that works.

**Comment by Norde** [comment] 2020-07-17 17:29
It's a fresh install of latest openhabian release (with online update at initial conf).

I can't retrieve Node version, cmd return "Illegal instruction".
It seems the apt based install of Node retrieve wrong version.

**Comment by ecdye** [comment] 2020-07-18 16:05
It should be pre-built. Here is a link <https://github.com/openhab/openhabian/actions/runs/172159549>

**Comment by Norde** [comment] 2020-07-18 16:06
@ecdye APT based install of Nodejs wont work for Rpi1 (and Rpi zero), as there's only armhf packages on raspbian repos.

Unless i'm missing something.

**Comment by ecdye** [comment] 2020-07-18 16:10
> @ecdye APT based install of Nodejs wont work for Rpi1 (and Rpi zero), as there's only armhf packages on raspbian repos.

I forgot about that, thanks for pointing that out. I'll look into it more in a bit.

**Comment by Norde** [comment] 2020-07-18 22:02
#990 don't resolve the issue.

However, @dceejay [updated update-nodejs-and-nodered script](https://github.com/node-red/linux-installers/issues/7) to force arm6 version if needed. This resolve the issue.

I still don't know what is causing this bug.

**Comment by ecdye** [comment] 2020-07-19 02:24
The issue is that NodeSource doesn't provide builds for anything older that armv7. I am issuing a patch, when the build completes I would be grateful if you could test and see if it works properly again. I'll post the link to the image when the build completes.

**Comment by ecdye** [comment] 2020-07-19 02:32
@Norde the build is now running, when it finishes the image should appear [here](https://github.com/ecdye/openhabian/actions/runs/174259245).

**Comment by Norde** [comment] 2020-07-19 08:49
Issue resolved.
node and npm works and update-nodejs-and-nodered (previous version) script too.

Thanks !

**Closed** 2020-07-19 14:42 UTC
Labels: bug-regression, optional component
