### ISSUE TITLE
Log Viewer Hard Coded IP address

### ISSUE THREAD

**Issue by houshasen** [openhab/openhabian#1514] opened 2021-04-28 08:44 UTC
Log Viewer link from OpenHabian instant became a broken link. The issue turned out to be original IP address from the time of installation was hardcoded.  This issue have been raised in the community forum in the past, but I did not see Bug Report filing here and the issue seems to be persistent.

## Expected Behavior

When IP address is changed, link should also be automatically updated. 

## Current Behavior
If I change IP address of the OpenHabian running server, Log Viewer Link remains to point to the original IP address:9001 therefore, it is a broken link.

## Possible Solution
1. Use environment variable like HOSTNAME to define the link in runtime.cfg file so the Log Viewer is always in sync. (idea is from official forum post back in 2018: https://community.openhab.org/t/solved-openhabian-wrong-url-for-frontail/38357/2
2. Use openhabian.local:9001 instead of IP address. This should at least take care, IP address only change, but it won't fix the issue if someone changes the local address name.
3. Add Add-on section for the Log Viewer Setting so at least user can manually change IP address if needs to via UI rather than going into CLI.

## Steps to Reproduce (for Bugs)
1. Originally DHCP assigned one IP address at the time of installation
2. I changed the IP to static address through my network controller.

## Context
As a new user to OpenHAB, I wanted to get a setup that is all in package; hence, I chose OpenHabian version. I have been encountering multiple issues/challenges setting up OpenHAB (though I still see a lots of potential to this system; hence, continue trying) but for these issues, I need an access to Log Viewer. 

I believe it is not infrequent for someone to change IP address perhaps because of DHCP to Static IP via controller, or making other network change. So user to see suddenly broken link to Log Viewer may be confusing. In fact, I thought originally Log Viewer itself was not running.

## Your Environment

* Version used: OpenHabian 3.0.1
* Environment name and version: Intel NUC ProxMox VM OpenHabian
* Operating System and version Accessed from Mac OS-X, Safari

**Comment by mstormi** [comment] 2021-05-09 19:28
You should have read in the [docs](https://github.com/openhab/openhabian/blob/main/docs/openhabian.md#networking) that switching to a static IP is not supported.  And again the number of people to want this is marginally small. There's not even a need to change IP on the box as you can do in your DHCP if you want to obtain a specific address.
Going beyond, frankly I don't understand what hardcoded "link" you mean that's supposed to be broken. I was able to change the ip of an openhabian system while running frontail, it kept working.
If your browser keeps resolving the name to the old address that's obviously a problem you caused yourself so you have to fix your DNS in that case.

**Closed by mstormi** 2021-05-09 19:28 UTC

**Comment by geeek76** [comment] 2022-07-04 07:12
@mstormi There are many reasons for having a static IP on your openhab. For ones. Not all DHCP servers supports reserved IP's. Another is like my OpenHab is located in a closed network without DHCP service and restricted access. It's not accessible from the internet and I don't have a DNS service.

The hardcoded link is when you click on other app's in the top right corner on the openhab frontpage (<your IP>:8080). The first app is the logviewer, but with a link to your old IP. The broken link in the meantime is a minor issue. The real issue is that the log view doesn't work after you set a static IP on OpenHab. Not even if you type the new URL (<your new IP>:9001) in a browser.

**Comment by mstormi** [comment] 2022-07-04 18:38
The point is openHABian does not support setting a static IP except via DHCP and that's clearly documented.
If you don't like that you can setup any DHCP of yours or use any other OS.
No static IP no (relevant) issue with the log viewer. I wouldn't mind incorporating a fix if you or anyone comes up with one but as you say yourself that's a minor issue and can be overcome by reinstalling.

**Comment by geeek76** [comment] 2022-07-04 20:33
It sounds like you are more focused on not supporting static IP than understanding the problem. The link is broken as soon as you change the IP. It doesn't matter whether you use reserved or unreserved DHCP or static IP. It's the change of the IP that breaks the link.

Beside that. I can't really see why OpenHabian shouldn't support static IP. I understand why it doesn't support changing the IP, but it shouldn't matter whether you assign an IP through reserved DHCP or static in the OS network config. I would expect assigning IP through unreserved DHCP would be a bigger issue than using static IP in the network config. The broken URL link would be in the lower end of the issues you will be facing when changing the IP.

Reinstalling is quite a big work for fixing a broken URL, which will break again as soon as your DHCP server assigns a new IP to your OpenHabian. There are several much simpler ways to fix the broken URL link. A simple script reading the current IP and setting it in the URL at boot would fix the issue. It's not rocket science if you actually looked at the problem instead of shooting down people when they mention static IP's.

Last but not least. My log viewer works again. I have no clue what made it work again, but suddenly it did and I haven't touched the network config at all after I changed it to static IP. The URL link is still broken although, but it doesn't really matter since I'm not using it anyway.

**Comment by mstormi** [comment] 2022-07-04 21:34
> It sounds like you are more focused on not supporting static IP than understanding the problem

I understood it's of marginal importance because it only affects a minimum of people. You're in fact the only one I heard of.

> I would expect assigning IP through unreserved DHCP would be a bigger issue than using static IP in the network config.

That's as far from true as can be. You have no clue how complex *automated* networking config is in openHABian.
There's reasons why static IP is not supported.

> It's not rocket science if you actually looked at the problem instead of shooting down people when they mention static IP's.

The since you obviously know all the stuff better than I do, why not debug your problem yourself and contribute a patch?

You deliberately ignored the prerequisites and nonetheless expect me to help you with that, then start blaming me that I don't want to.
I better don't comment on that. Just a reminder: this is OSS, the work of volunteers.
Please refrain from future communications.

**Comment by geeek76** [comment] 2022-07-04 22:25
> I understood it's of marginal importance because it only affects a minimum of people. You're in fact the only one I heard of.
I'm not the one who reported this issue.

> Then since you obviously know all the stuff better than I do, why not debug your problem yourself and contribute a patch?
What is there to debug? It's a URL link that gets broken when you change the IP on the OpenHabian installation. It doesn't matter whether the change is done using DHCP or static assignment. Have you even found the link and looked at it?

> You deliberately ignored the prerequisites and nonetheless expect me to help you with that, then start blaming me that I don't want to. I better don't comment on that. Just a reminder: this is OSS, the work of volunteers. Please refrain from future communications.
I really don't care whether the problem is fixed or not. I'm just trying to explain to you that you have completely misunderstood the issue.
And talk about blaming people. Try have a look at your post on May 9 2021. You are so focused on OpenHabian not supporting static IP that you completely overlook that the issue has NOTHING to do with static IP, but is down to a CHANGE of IP. A change that is much more likely to happen when IP's are assigned through unreserved DHCP than if assigned static through network config. In fact. The solution you propose is exactly what houshasen did. He reserved an IP for his OpenHabian in his network controller = DHCP server.
