### ISSUE TITLE
Waiting for dpkg/apt to get ready... hang

### ISSUE THREAD

**Issue by v-sante** [openhab/openhabian#736] opened 2019-10-09 11:14 UTC
Platform information: Raspberry PI B3+
openHAB version: v.15, downloaded from openhab, flashed using etcher to 64G microSD card.
Issue of the topic: The log for installation commences but hangs on the following line (all previous lines end OK):
Waiting for dpkg/apt to get ready...
The log remains available for about 5 minutes, and then it is no longer possible to connect to the log (unreachable).

I have waiting up to an hour twice but it never returns.

What is going wrong at this stage and how to I begin to fix it?

**Comment by andygoyvaerts** [comment] 2019-10-27 21:01
Hi I'm having the same problem. Raspberry Pi 4 with V1.5 downloaded from openhab, flashed using etcher to 32G microSD card.
Anyone a solution?

**Comment by Harphme** [comment] 2019-10-30 06:44
Same to me: Raspberry Pi 4 with V1.5 downloaded from openhab, flashed using etcher to 16G microSD card.

**Comment by andygoyvaerts** [comment] 2019-11-02 14:39
No one?

**Comment by v-sante** [comment] 2019-11-02 21:01
Hi - in the end it did just work for me. I did change the power cable for the raspberry pi to the official one, to avoid any risk of that interfering. I also connected it direct to my main router, so it would not depend on connecting through my more complex home network. But I can’t say why in the end it just worked. I just kept trying.

**Comment by mstormi** [comment] 2019-11-03 13:41
As noone seems to be able to reproduce this or to bring any substantial information that might help to solve, please close this issue.
We have changes in the pipe to allow for more debugging so once those are in and the problem happens again, you can open another issue.

**Closed** 2019-11-03 21:43 UTC
