### ISSUE TITLE
Is miflora-mqtt-daemon optional component install script broken?

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhabian#230] opened 2017-11-03 14:17 UTC
https://github.com/ThomDietrich/miflora-mqtt-daemon
https://community.openhab.org/t/xiaomi-mi-flora-plant-sensor-mqtt-client-daemon/33119

**Comment by aymeric106** [comment] 2018-05-07 14:02
Hello, I've installed the current openhabian release, switched to a nightly build of openhab, and then install the optional component mi flora you wrote.
Something is wrong with the installation I think. 
When testing

`python3 /opt/miflora-mqtt-daemon/miflora-mqtt-daemon.py`

It's not working, complaining about the coloroma module not being found.

I've done the same thing, except I manually installed your daemon with

``sudo apt install git python3 python3-pip bluetooth bluez``
``git clone https://github.com/ThomDietrich/miflora-mqtt-daemon.git /opt/miflora-mqtt-daemon``
``cd /opt/miflora-mqtt-daemon``
``sudo pip3 install -r requirements.txt``

And it worked

```

**Comment by EliasGabrielsson** [comment] 2018-12-19 13:35
@ThomDietrich if you have spare time could you look into this?
Otherwise push it forward to version 1.6

**Comment by EliasGabrielsson** [comment] 2019-06-28 21:45
@ThomDietrich bumbing this.
Shall we drop this feature?

**Comment by ThomDietrich** [comment] 2019-06-29 10:21
I would like to fix this bug and will have the time to do so in 2-3 weeks. However as I still can't promise anything how about the following: we remove the menu entry for the component now and I can add it back in as soon as I got around to fixing it. Wdyt?

**Comment by EliasGabrielsson** [comment] 2019-06-30 08:06
Sounds good. 
Trying to do a house cleaning for version 1.5 so promised features actually works.
That is why am so conservative about adding new functions and features.

We will see if it is fixed when it times to release 1.5

**Comment by EliasGabrielsson** [comment] 2019-08-04 18:03
I can confirm that this package are giving error "FAILED" during installation. 
The message on menu however says "success". Investigate and repair.

**Comment by holgerfriedrich** [comment] 2019-08-08 20:43
@EliasGabrielsson To successfully start the service after installation, a change to `/opt/miflora-mqtt-daemon/config.ini` is required. This is explained in the dialog after installation.

The FAILED shown during installation is because service start cannot work with the given config.ini.
First, mqtt service is required (without config change at localhost w/o auth). Second, at least one sensor needs to be defined.
`journalctl -xe` is not much helpful to debug the daemon start, running the daemon manually `/opt/miflora-mqtt-daemon/miflora-mqtt-daemon.py` shows error output.

I got it running (as far as I could get w/o hardware) on Raspbian Buster/RPi 3B+. IMHO [CURRENTLY BROKEN] can be removed.

Two options: 
a) to remove service start from installation
b) ask user for mqtt settings from openhabian-config, and add a default sensor to config.ini

**Comment by EliasGabrielsson** [comment] 2019-08-08 21:54
Well investigated 🥇 
As @ThomDietrich wrote this plugin and have the actual gear I will let him answer you.
I will just spread disinformation and bad judgement 😄

**Comment by msebald** [comment] 2020-04-14 11:38
For me running openHAB and openhabian-config on Debian Buster (upgraded vom Stretch) the install/upgrade script worked, too.

But I had to install the Debian package libglib2.0-dev first as bluepy building failed otherwise because the file glib.h was missing.

Maybe you somehow want to add libglib2.0-dev to the mandatory packages, install it and remove the broken warning after this.

**Comment by mstormi** [comment] 2020-04-17 07:41
@ThomDietrich could you please re-check

**Comment by ThomDietrich** [comment] 2020-04-17 12:14
Will do! Also check everything else this weekend!

**Comment by mstormi** [comment] 2020-04-20 09:16
Long weekend ? ;-)

**Comment by mstormi** [comment] 2020-06-23 21:20
@ThomDietrich @holgerfriedrich could you please test and state if there's anything to be fixed or not

**Comment by ThomDietrich** [comment] 2020-06-24 07:04
Hey @mstormi!
I didn't test the install script but I've tested the daemon itself recently. It is a bit improved and working once again.

**Comment by mstormi** [comment] 2020-06-24 09:42
Glad to hear from you. Hope the virus didn't strike you.

**Comment by mstormi** [comment] 2020-06-24 09:52
Just tried installing on a RPi2 (it has no Bluetooth). That at least went fine without errors.
The miflora daemon does not run though.  I uncommented a sensor line in config.ini when it said there's no sensors but still, see output below.
May I nonetheless assume that install was successfull hence we can close this issue ?

```
[11:46:17] root@devpi:/opt/miflora-mqtt-daemon# systemctl status miflora.service
● miflora.service - Xiaomi Mi Flora Plant Sensor MQTT Client/Daemon
   Loaded: loaded (/etc/systemd/system/miflora.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2020-06-24 11:46:15 CEST; 6s ago
     Docs: https://github.com/ThomDietrich/miflora-mqtt-daemon
  Process: 21903 ExecStart=/usr/bin/python3 /opt/miflora-mqtt-daemon/miflora-mqtt-daemon.py (code=exited, status=1/FAILURE)
 Main PID: 21903 (code=exited, status=1/FAILURE)
   Status: "Jun 24 11:46:15 - Configuration accepted."

Jun 24 11:46:15 devpi systemd[1]: miflora.service: Service RestartSec=100ms expired, scheduling restart.
Jun 24 11:46:15 devpi systemd[1]: miflora.service: Scheduled restart job, restart counter is at 5.
Jun 24 11:46:15 devpi systemd[1]: Stopped Xiaomi Mi Flora Plant Sensor MQTT Client/Daemon.
Jun 24 11:46:15 devpi systemd[1]: miflora.service: Start request repeated too quickly.
Jun 24 11:46:15 devpi systemd[1]: miflora.service: Failed with result 'exit-code'.
Jun 24 11:46:15 devpi systemd[1]: Failed to start Xiaomi Mi Flora Plant Sensor MQTT Client/Daemon.

```

**Comment by ThomDietrich** [comment] 2020-06-24 09:55
No I'm fine, thanks! How are you?
With the whole lockdown and homeoffice in place I changed my lifestyle to stay sane. Sorry I never got back to you but I'm very happy to see that you guys are in full control of the situation!!! 👏  Feel free to mention me wherever you would like my input or need another pair of eyes! 😃

**Comment by ThomDietrich** [comment] 2020-06-24 10:01
Had a look at the code. It should work but I'll try soon. For now could you just re-add it and remove the "NOT WORKING" comment?

**Comment by mstormi** [comment] 2020-06-24 10:07
Not sure what you mean by "re-add". I'm not really into this thing, just validating open issues to get those remaining ones done.
May I suggest you create a PR to remove the comment (and to eventually fix stuff) yourself when you have tried installing.

**Comment by mstormi** [comment] 2020-07-05 15:33
@ThomDietrich did you validate this works? Can we close it ?

**Comment by mstormi** [comment] 2020-09-04 20:05
@ThomDietrich did you validate this works? Can we close it ?

**Comment by mstormi** [comment] 2020-09-16 20:00
no feedback means no problems I guess.
Reopen if you disagree.

**Closed by mstormi** 2020-09-16 20:00 UTC
Labels: bug-regression
