### ISSUE TITLE
Frontail fails to install on Debian with 'openhabian-config unattended'

### ISSUE THREAD

**Issue by juanhaywood** [openhab/openhabian#1381] opened 2021-01-05 08:54 UTC
## Issue information:
Frontail fails to install on Debian with 'openhabian-config unattended'. Seems to be due to npm being missing.

## Debug information:
[OH3DebNew4.log](https://github.com/openhab/openhabian/files/5769074/OH3DebNew4.log)

## System information:
OS: Debian
HW: Hyper-v VM

cat /etc/os-release output:
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

uname -m output:
i686

**Comment by juanhaywood** [comment] 2021-01-05 09:00
I've manually installed npm with `sudo apt install`, and then run Menu Item 21. I'm now able to access frontail in the browser, but it doesn't seem to be tailing the logfiles. 

[OH3DebNew4.1.log](https://github.com/openhab/openhabian/files/5769101/OH3DebNew4.1.log)


![image](https://user-images.githubusercontent.com/53084642/103626478-e8616700-4f44-11eb-91e2-b07ce88e5c0a.png)

**Comment by mstormi** [comment] 2021-01-05 10:26
Menu 21 / unattended both use the same frontail_setup() routine and should install npm if it is not there.

Get a log with debugmode=maximum to see why that didn't work on your system.
(uninstall npm first then menu 21)

**Comment by juanhaywood** [comment] 2021-01-05 11:30
It doesn't seem as if menu 21 installs npm. 

Logs from a clean install of Debian, from the point right after running `openhabian-config unattended`:
[OH3DebNew5.log](https://github.com/openhab/openhabian/files/5769861/OH3DebNew5.log)

**Comment by dimmenhau** [comment] 2021-01-05 14:16
I have the problem that Frontail no longer displays on my Raspberry either. I also just reinstalled OH3 on the server and the problem is there too.

I also get the following message in the DevTool of Chrome:
    index.js:83 WebSocket connection to 'ws://192.168.0.51:9001/socket.io/?EIO=3&transport=websocket' failed: Error during WebSocket handshake: Unexpected response code: 400

**Comment by mstormi** [comment] 2021-01-05 15:21
> I have the problem that Frontail no longer displays on my Raspberry either

Do not cross post into anything vaguely related please. Thank you.

**Comment by mstormi** [comment] 2021-01-05 15:26
@juanhaywood See line 16 of /opt/openhabian/functions/nodejs-apps.bash, to install npm is commented out for some reason,
maybe because npm is part of the Raspberry image. Uncomment the line and retry menu 21 (do not let openhabian-config update itself as that would overwrite your line change)

**Comment by dimmenhau** [comment] 2021-01-05 15:37
> Do not cross post into anything vaguely related please. That is absolutely not helpful and this is not a discussion board. Thank you.

i'm sorry, i make a new issue open

**Comment by juanhaywood** [comment] 2021-01-05 16:03
> Uncomment the line and retry menu 21

This fixed the issue with npm not being installed. Tested both with menu 21, and then again with a clean Debian installation and unattended setup. It worked in both cases. However, Frontail is still not tailing any files. Should I log a separate issue for this?:

![image](https://user-images.githubusercontent.com/53084642/103668868-465f7000-4f80-11eb-8eda-268f9c200299.png)

**Comment by mstormi** [comment] 2021-01-05 16:56
need to fix npm install first.
below is what happens on RPi when I uncomment the line

```
+ echo -e '\n\033[90;01m$ apt-get install --yes npm \033[39;49;00m'

$ apt-get install --yes npm
+ apt-get install --yes npm
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 npm : Depends: nodejs (>= 6.11~) but it is not going to be installed
       Depends: node-abbrev (>= 1.1.1~) but it is not going to be installed
       Depends: node-ansi-regex (>= 3.0~) but it is not going to be installed
       Depends: node-ansistyles (>= 0.1.3~) but it is not going to be installed
       Depends: node-aproba (>= 1.2~) but it is not going to be installed
       Depends: node-archy (>= 1.0~) but it is not going to be installed
       Depends: node-cacache (>= 10.0.4~) but it is not going to be installed
       Depends: node-bluebird (>= 3.5.1~) but it is not going to be installed
       Depends: node-call-limit (>= 1.1~) but it is not going to be installed
       Depends: node-chownr (>= 1.0.1~) but it is not going to be installed
       Depends: node-config-chain (>= 1.1.11~) but it is not going to be installed
       Depends: node-detect-indent (>= 5.0~) but it is not going to be installed
       Depends: node-detect-newline (>= 2.1~) but it is not going to be installed
       Depends: node-editor (>= 1.0~) but it is not going to be installed
       Depends: node-fs-vacuum (>= 1.2.10~) but it is not going to be installed
       Depends: node-fs-write-stream-atomic (>= 1.0.10~) but it is not going to be in
stalled
```

**Comment by mstormi** [comment] 2021-01-05 17:16
> Frontail is still not tailing any files. Should I log a separate issue for this?:

Only if you can reproduce this with a fresh install of the latest openHABian code please (openHAB3 branch) 

Pls do
```
source /opt/openhabian/functions/helpers.bash
set -x
is_rapios
is_raspbian
is_debian

**Comment by mstormi** [comment] 2021-01-05 17:26
npm not installed on non-RPi should be fixed by https://github.com/openhab/openhabian/commit/ecb9bb29fc1eb8e42ddf43886be3edbba0bdd7fe

**Closed by mstormi** 2021-01-05 17:26 UTC

**Comment by juanhaywood** [comment] 2021-01-05 18:48
> source /opt/openhabian/functions/helpers.bash
> set -x
> is_rapios
> is_raspbian
> is_debian

This is new to me; do I just run each command individually in the shell? Do I do this before or after a fresh installation of the latest openHABian code?

**Comment by mstormi** [comment] 2021-01-05 18:49
yes shell. doesn matter when. its just diagnosis

**Comment by juanhaywood** [comment] 2021-01-05 18:51
Ok, did a fresh installation, and no luck with getting Frontail to tail the log files. Still blank output. 

Diagnosis info:
```
[19:46:07] root@openhab3deb:/home/juan# source /opt/openhabian/functions/helpers.bash
[19:46:34] root@openhab3deb:/home/juan# set -x
[19:46:39] root@openhab3deb:/home/juan# is_rapios
+ is_rapios
bash: is_rapios: command not found
[19:46:43] root@openhab3deb:/home/juan# is_raspbian
+ is_raspbian
+ [[ '' == \r\a\s\p\b\i\a\n ]]
++ cat /etc/os-release
+ [[ PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/" =~ Raspbian ]]
+ return 1
[19:46:51] root@openhab3deb:/home/juan# is_debian
+ is_debian
+ [[ '' == \d\e\b\i\a\n ]]
++ cat /etc/os-release
+ [[ PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/" =~ ID_LIKE=debian ]]
+ return 1

```

**Comment by mstormi** [comment] 2021-01-05 18:59
please show is_raspios (that was was a typo)

**Comment by mstormi** [comment] 2021-01-05 21:04
so install works now hence this issue is closed.
No need to open another one there's already a duplicate

**Comment by juanhaywood** [comment] 2021-01-06 07:37
> please show is_raspios (that was was a typo)

```
+ is_raspios
+ [[ '' == \r\a\s\p\i\o\s ]]
+ is_raspbian
+ [[ '' == \r\a\s\p\b\i\a\n ]]
++ cat /etc/os-release
+ [[ PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/" =~ Raspbian ]]
+ return 1
++ cat /etc/os-release
+ [[ PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/" =~ Raspberry Pi OS ]]
++ cat /boot/issue.txt
cat: /boot/issue.txt: No such file or directory
+ [[ '' =~ Raspberry Pi reference ]]
+ return 1

```
