### ISSUE TITLE
First-boot failed on Raspi 3B+ : Failed to start /etc/rc.local Compatibility

### ISSUE THREAD

**Issue by lsteelandt** [openhab/openhabian#648] opened 2019-08-06 17:40 UTC
First boot after installation an SD card with openhabian-pi-raspbian-201908050414-gitca0976f-crc6a66b5a1.img, failed. 

The problem seems to come while executing " Starting /etc/rc.local Compatibility... "
Failed to start /etc/rc.local Compatibility.

Is it suitable for a Raspberry pi 3 model B+   ?

**Comment by holgerfriedrich** [comment] 2019-08-06 17:46
It should work on a 3B+, this is the same setup I am currently using....

**Comment by mstormi** [comment] 2019-08-06 18:08
Saw someone else to mention this https://community.openhab.org/t/raspberry-pi-4-openhabian-v1-5-0-error-w-installing-zulu-embedded-openjdk/79370
See there for a quick fix.

**Comment by mstormi** [comment] 2019-08-07 21:34
@EliasGabrielsson will you create an image to contain java install fix ?

**Comment by lsteelandt** [comment] 2019-08-08 04:54
@mstormi for the issue describe on this feed, I don't think it's a matter of java installation failure. 
But for the feed you give the link yes. 
Maybe the next image will hold other fixes that resolve my issue (hope to :wink:).

**Comment by EliasGabrielsson** [comment] 2019-08-08 14:25
I don't get why we should build an new image. To part which were broken, i.e. the failed downloaded Java package have been patched and it not part of the `first-boot.sh` script.

The error here should be resolved by easily flash a new image from scratch.

**Comment by mstormi** [comment] 2019-08-12 16:50
> The part which were broken [...] is not part of the `first-boot.sh` script.

Wasn't sure of that myself so ok no need for another image.

@lsteelandt did the recent updates fix your problem ?

**Comment by lsteelandt** [comment] 2019-08-12 17:27
@mstormi oh, i didn't notice that there is a new update.  I will try when I will get a new raspberry.  The one I send for this installation is not yet on my hand

**Comment by EliasGabrielsson** [comment] 2019-08-17 10:41
Hi @lsteelandt!
Please make another try with the installation and we take it from there. 👍

**Comment by mstormi** [comment] 2019-09-06 11:23
Got this very same error when testing latest image against a RPi 2

syslog:
```
Sep  6 11:10:11 openhab systemd[1]: rc-local.service: Control process exited, code=exited, status=1/FAILURE
Sep  6 11:10:11 openhab systemd[1]: rc-local.service: Failed with result 'exit-code'.
Sep  6 11:10:11 openhab systemd[1]: Failed to start /etc/rc.local Compatibility.

```
root@openhab:/home/openhabian# systemctl status rc.local
● rc-local.service - /etc/rc.local Compatibility
   Loaded: loaded (/lib/systemd/system/rc-local.service; enabled-runtime; vendor preset: enabled)
  Drop-In: /lib/systemd/system/rc-local.service.d
           └─debian.conf
           /etc/systemd/system/rc-local.service.d
           └─ttyoutput.conf
   Active: failed (Result: exit-code) since Fri 2019-09-06 11:10:11 BST; 1h 12min ago
     Docs: man:systemd-rc-local-generator(8)

Sep 06 11:01:13 openhab systemd[1]: Starting /etc/rc.local Compatibility...
Sep 06 11:10:11 openhab systemd[1]: rc-local.service: Control process exited, code=exited, status=1/FAILURE
Sep 06 11:10:11 openhab systemd[1]: rc-local.service: Failed with result 'exit-code'.
Sep 06 11:10:11 openhab systemd[1]: Failed to start /etc/rc.local Compatibility.

**Comment by SnowPatrolXV** [comment] 2019-10-17 21:04
Hi,

I have also the same issue.

Have you fixed the problem ?

**Comment by florianeggert** [comment] 2019-11-12 21:38
Hallo,
i have the same problem all the time. Do you have another idea to fix the problem?

**Comment by dreameruk76** [comment] 2020-01-06 08:58
I've experienced the same errot but I've found the fault is something to do with WiFi. Once I connected my Pi to the ethernet, it worked perfectly. I didn't change anything only how it connects to the internet.

Hope that helps you find the bug.

**Comment by incrazyboyy** [comment] 2020-03-14 18:40
I also got this error message. Also, the file /opt/afterfirstboot.lock was never created after the first-boot.bash script failed. So every reboot resulted in a new install procedure. 
Running "touch /opt/afterfirstboot.lock" fixed that for me.

**Comment by thijz** [comment] 2020-04-06 07:57
hit the same issue.  touching the afterfirstboot file fixed it.
note that i did run a apt update and upgrade manually after the first failed attempt, bu i guess that doens really matter much

**Comment by HeneryH** [comment] 2020-04-14 18:50
Same issue here with the first-boot.bash failing with the rc-local.service error.

I'll have to dig up a keyboard somewhere to try to fix it.

**Comment by HeneryH** [comment] 2020-04-14 20:28
I think I am going to scrap the installers and go manual install.

**Comment by holgerfriedrich** [comment] 2020-04-15 22:59
The error message is quite misleading. rc.local compatibility is the way how openhabian installer is hooked into the boot process. Whenever the installer script exits with error, the service claims to fail.
So what you described here is the effect, not the root cause.

Can you go back in the log to see what actually failed?

**Comment by HeneryH** [comment] 2020-04-16 00:20
Sorry, I started from scratch with a clean raspian install with the manual
steps.

I'm curious about some of the add-on packages the image uses.  Some sd-card
optimization stuff and so forth that I will research.

**Comment by jwsp1** [comment] 2020-04-21 16:52
Getting the same error. Hope someone who has a solution will share it with us :)

**Comment by holgerfriedrich** [comment] 2020-04-21 16:56
Can you give more information about the install? Any hints in first-boot.log what could have failed?
And as always: which pi model, lan or wifi, etc....
Thanks.

**Comment by jwsp1** [comment] 2020-04-21 17:06
> @jwsp1 Can you give more information about the install? Any hints in first-boot.log what could have failed?
> And as always: which pi model, lan or wifi, etc....
> Thanks.

Sorry, thought the origin of the bug was already known.
I'll share my first-boot.log, I guess "Setting timezone based on IP geolocation... FAILED" is no tragedy, but rather "Installing additional needed packages... FAILED" is one.
Using RaspberryPi Model 3B+, LAN, Samsung EVO Plus 64GB SDcard. Tried several times.

---------
2019-07-10_01:21:35_BST [openHABian] Starting the openHABian initial setup.
2019-07-10_01:21:36_BST [openHABian] Storing configuration... OK
2019-07-10_01:21:36_BST [openHABian] Starting webserver with installation log... OK
2019-07-10_01:21:45_BST [openHABian] Changing default username and password... OK
2020-04-21_17:13:08_BST [openHABian] Setting up Ethernet connection... OK
2020-04-21_17:13:08_BST [openHABian] Ensuring network connectivity... OK
2020-04-21_17:13:11_BST [openHABian] Waiting for dpkg/apt to get ready... OK
2020-04-21_17:14:11_BST [openHABian] Updating repositories and upgrading installed packages... OK
2020-04-21_17:23:47_BST [openHABian] Installing git package... OK
2020-04-21_17:24:31_BST [openHABian] Cloning myself... OK
2020-04-21_17:24:41_BST [openHABian] Executing 'openhabian-setup.sh unattended'... 
2020-04-21_17:24:41_BST [openHABian] Checking for root privileges... OK
2020-04-21_17:24:47_BST [openHABian] Loading configuration file '/etc/openhabian.conf'... OK
2020-04-21_17:24:47_BST [openHABian] Setting timezone based on IP geolocation... FAILED
2020-04-21_17:26:22_BST [openHABian] Setting locale based on openhabian.conf... OK
2020-04-21_17:27:53_BST [openHABian] Setting hostname of the base system... OK
2020-04-21_17:27:53_BST [openHABian] Setting the GPU memory split down to 16MB for headless system... OK
2020-04-21_17:27:53_BST [openHABian] Enabling Audio output... OK
2020-04-21_17:27:53_BST [openHABian] Installing basic can't-be-wrong packages (screen, vim, ...)... OK
2020-04-21_17:29:24_BST [openHABian] Installing additional needed packages... FAILED
2020-04-21_17:30:04_BST [openHABian] Initial setup exiting with an error!

**Comment by mstormi** [comment] 2020-04-21 18:32
set mode=debug_maximum in /etc/openhabian.conf and reboot

**Comment by jwsp1** [comment] 2020-04-22 09:31
Oddly, it works now. Haven't changed anything besides using another SD-card (32GB instead of 64GB) and trying the third time...

**Comment by mstormi** [comment] 2020-06-16 13:47
All, I believe this is fixed in current openHABian so will close this.
Please reopen I case you encounter this again, but if so, take advantage of openHABian's new debug mode feature (`debugmode=maximum` in `/boot/openhabian.conf`, see docs) to get verbose output This is needed to pinpoint where the problem ultimately really is.
Note that the message about /etc/rc.local Compatibility is merely a symptom not the problem itself.

**Closed by mstormi** 2020-06-16 13:47 UTC
Labels: bug
