### ISSUE TITLE
VPN to access configuration files from remote

### ISSUE THREAD

**Issue by Melkor82** [openhab/openhabian#257] opened 2017-12-06 19:39 UTC
As stated here in the lastest posts [https://community.openhab.org/t/dropbox-configuration-with-oh2/30300/2](url)  dropbox binding is no longer working since api version 2. I am often away from home and have plenty of time. I would love to access my config files. I have come up to some Own cloud based free service like TONIDO. I tried to install it but having some errors. 
That's all my programming skills got me, i am not sayng this should be the one but i think some cloud based config file sharing should be implemented on openhabian. 
Thanks for the attention

**Comment by ThomDietrich** [comment] 2017-12-10 19:34
Out of coincidence I was playing around with owncloud one-two days before your post. I worked out a webDAV based approach and sadly ran into an issue with the way it would then be synchronized with the actual openHAB config folder. The next try would probably be to try define a cron-based regular execution of owncloudcmd. Not sure when I'll have the time.

Here's my suggestion. Please create a new thread in the openHAB community. Ask for a solution on how to sync the openHAB configuration (ideally the collected content of `/srv`) with the owncloud. There are probably folks out there with a fully working solution. If we know about it, it would be easy to add a function for openHABian.

Please link the thread here!

Best!

**Comment by Melkor82** [comment] 2017-12-11 02:14
Well i resolved installing HAMACHI for raspberry provided by LOGMEIN. It add virtual net adapter so i can access file from all over the world and plus it’s like being on the same network, not having to port forward ports anymore. I will try to have it installed on my mobile too so i can avoid the use of myopenhab cloud. Installation is pretty straight forward

**Comment by ThomDietrich** [comment] 2017-12-11 10:42
That's yet another solution. I'm using openvpn for that. The issue is about owncloud though, correct!?

**Comment by mstormi** [comment] 2020-04-17 07:40
@EliasGabrielsson @holgerfriedrich how do you think we should proceed with this ?
Essentially it'`s just the idea to include a VPN solution with openHABian, but no good proposal or even implementation in sight.

**Comment by holgerfriedrich** [comment] 2020-04-17 20:31
@mstormi  I think this is out of scope for now. We aim at easy installs.
This is something advanced users can handle on their own, and there are many approaches (sshfs, vpn, owncloud, samba, git, ...). New users will use local network via samba or similar.
VPN itself is not a bad idea, but I would not like the idea to run a VPN server on the openhabian machine. Should be somewhere else in my home network.

**Comment by mstormi** [comment] 2020-04-17 21:58
Agree. Anyone to propose a VPN solution shall open a new thread.

**Closed by mstormi** 2020-04-17 21:58 UTC
Labels: help wanted, optional component
