### ISSUE TITLE
Installation of InfluxDB and Grafana fails to complete

### ISSUE THREAD

**Issue by thetonto** [openhab/openhabian#760] opened 2019-11-05 01:22 UTC
New install of Openbian onto Raspberry Pi 4.  
After entering all the password error message appears that operation could not be completed and please report to the team.  No other details were given.

Checking the install it appears to have failed at creating the database in influx as when I tried to configure persistence it failed as no database.  Had to go back in via command line, create admin account, then create the database and users for openhab and grafana.

**Comment by dmize** [comment] 2019-11-05 22:05
I just had this same issue on a new install on RPI 4 as well.

**Comment by TOM01011963** [comment] 2019-11-12 15:39
Exactly the same with me, also on a Raspberry Pi 4.
The installation is nearly completed until a message appears, there is something wrong with the admin user of grafana... and a window pops up to open an issue here.

**Comment by AndyHowell** [comment] 2019-11-24 22:07
I've made some progress on this. The grafana admin passwork needs to be reset before it is set. I was also having problem with influxdb install failing. This turned out to be a timing issue. I increased the delay after restarting it to 30 seconds.

<code>
<pre>
diff -u influxdb+grafana.bash /opt/openhabian/functions/influxdb+grafana.bash
--- influxdb+grafana.bash	2019-11-24 15:01:05.426343471 -0600
+++ /opt/openhabian/functions/influxdb+grafana.bash	2019-11-24 15:02:15.844404891 -0600
@@ -153,6 +153,8 @@
   if [ -n "$influxdb_admin_username" ]; then # is set, configure database and application users
     echo -n "Setup of inital influxdb database and InfluxDB users... "
     echo -n ""
+    echo "Sleeping for 10 sec"
+    sleep 10 
     influxdb_database_name="openhab_db"
     curl --user "$influxdb_admin_username:$influxdb_admin_password" --insecure $influxdb_address/query --data-urlencode "q=CREATE DATABASE $influxdb_database_name" || FAILED=1
     curl --user "$influxdb_admin_username:$influxdb_admin_password" --insecure $influxdb_address/query --data-urlencode "q=CREATE USER openhab WITH PASSWORD '$influxdb_openhab_password'" || FAILED=1
@@ -227,10 +229,10 @@
     cond_redirect systemctl enable influxdb.service
     sleep 2
     cond_redirect systemctl restart influxdb.service
-    sleep 10
+    sleep 30
     if [ $FAILED -eq 1 ]; then echo -n "FAILED "; else echo -n "OK "; fi
     echo -n "Configure InfluxDB admin account... "; echo -n ""
-    curl --insecure $influxdb_address/query --data-urlencode "q=CREATE USER admin WITH PASSWORD '$1' WITH ALL PRIVILEGES" || FAILED=1
+    cond_redirect curl --insecure $influxdb_address/query --data-urlencode "q=CREATE USER admin WITH PASSWORD '$1' WITH ALL PRIVILEGES" || FAILED=1
     if [ $FAILED -eq 1 ]; then echo -n "FAILED "; else echo -n "OK "; fi
     echo -n "Configure listen on localhost only... "; echo -n ""
     cond_redirect sed -i -e '/^# Determines whether HTTP endpoint is enabled./ { n ; s/^# enabled = true/enabled = true/ }' /etc/influxdb/influxdb.conf
@@ -267,6 +269,11 @@
   if [ $FAILED -eq 2 ]; then echo -n "FAILED "; return 2; else echo -n "OK "; fi
   cond_echo ""

 </pre>
<pre>
+  echo "Fixing paths for debian"
+  cond_redirect ln -s /var/lib/grafana  /usr/share/grafana/data
+  cond_redirect ln -s /var/log/grafana /usr/share/grafana/data/logs
+  echo -n "Resetting admin password"
+  cond_redirect grafana-cli admin reset-admin-password admin
   echo -n "Updating Grafana admin password..."
   curl --user admin:admin --header "Content-Type: application/json" --request PUT --data "{\"password\":\"$1\"}" http://localhost:3000/api/admin/users/1/password || FAILED=2
   if [ $FAILED -eq 2 ]; then echo -n "FAILED "; return 2; else echo -n "OK "; fi
</pre>
</code>

I'm still not able to select openhab_home as a data source. It wants a user name and password. I tried all the ones I configure.

I found the hint about resetting the password here: https://github.com/grafana/grafana/issues/12638


Andy

**Comment by EliasGabrielsson** [comment] 2019-12-03 16:41
Thanks for looking into this.
I will try to get some time of during the holidays and patch this.
But if you would like to contribute with a PR they are more then welcome

**Comment by AndyHowell** [comment] 2019-12-03 20:05
Elias,

I can put together a PR in the next day or two.

Thanks,

Andy

**Comment by AndyHowell** [comment] 2019-12-05 09:55
Elias,

After much mucking about, I failed to reproduce this under docker. I will have to try on a raspberry pi.

I did run into a number of issues getting the docker image to run. Much of it was likely my ignorance of docker, however I did have a problem with the Dockerfile. I'm not sure that this made a difference. During the build, I got:

```
Get:1 http://deb.debian.org/debian stretch/main amd64 libonig4 amd64 6.1.3-2 [146 kB]
Get:2 http://deb.debian.org/debian stretch/main amd64 libjq1 amd64 1.5+dfsg-1.3 [123 kB]
Get:3 http://deb.debian.org/debian stretch/main amd64 jq amd64 1.5+dfsg-1.3 [58.6 kB]

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'root@257a935190a1.(none)')
warning: etckeeper failed to commit changes in /etc using git
debconf: delaying package configuration, since apt-utils is not installed
```
To keep git and etckeeper happy, I changed the Dockerfile to install git and then add the global config:

```
RUN apt-get install -y git
RUN git config --global user.email "openhabian@openhab.local"
RUN git config --global user.name "openhabian"
```
When doing the install, I encountered this:

```
2019-12-05_16:55:21_JST [openHABian] Script '/boot/first-boot.bash' failed.
andy@dokodemo:~/src/openhab/openhabian$ docker exec -it install-test bash 
OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused "chdir to cwd (\"/opt/openhabian\") set in config.json failed: no such file or directory": unknown
```

That was caused by first-boot.bash deleting the current directory of /opt/openhabian

```diff --git a/build-image/first-boot.bash b/build-image/first-boot.bash
index a6168f5..e0eee93 100755
--- a/build-image/first-boot.bash
+++ b/build-image/first-boot.bash
@@ -146,6 +146,7 @@ echo -n "$(timestamp) [openHABian] Installing git package... "
 if apt-get -y install git &>/dev/null; then echo "OK"; else echo "FAILED"; fail_inprogress; fi
 
 echo -n "$(timestamp) [openHABian] Cloning myself... "
+cd /
 if [ -d /opt/openhabian/ ]; then rm -rf /opt/openhabian/; fi
 if git clone -b master https://github.com/openhab/openhabian.git /opt/openhabian; then echo "OK"; else echo "FAILED"; fail_inprogress; fi
 ln -sfn /opt/openhabian/openhabian-setup.sh /usr/local/bin/openhabian-config
```
I also changed the Dockerfile to use buster instead of stretch, since that is what was running on the rasberry pi. Lastly, I'm doing this against the milestone release. I think I was running 2.5M4 or M5 when I first encountered the Grafana install error. The test above was against 2.5M6.

Let me know if I'm doing anything stupid with the docker setup. I used the instructions in CONTRIBUTING.md as my guide.

Thanks,
Andy

**Comment by bbogdanmircea** [comment] 2020-01-15 08:53
Also having the same problem on my pi4, tried to reset admin but keep on receiving some funny error for the grafana-cli command

**Comment by bbogdanmircea** [comment] 2020-01-15 15:53
Is it possible to manually install InfluxDB and Grafana and then create also manually all needed databases and connections until this issue is solved in the scripts?

**Comment by m4rky-m4rk** [comment] 2020-01-15 19:06
I was contemplating doing the manual install too. I successfully setup Influx and Grafana for Openhabian openHAB 2.4 on a RPi3 and now I try to setup it up on v2.5 , RPi4 with the config tool but without success. I get 'No data in Grafana'.  I was wondering if the current instructions would also work for Buster. Files in same locations etc,. Or should I  just wait until its fixed.

**Comment by AndyHowell** [comment] 2020-01-15 19:28
I was able to do the install through a combination of modifying the script and doing step listed on the web page for the creation of the tables etc. Sorry I don't remember the details. I currently have it running on v2.5 on a RPi4. Hopefully my comments above will serve a guide. You certainly could do each of the steps in the script manually.

**Comment by AndyHowell** [comment] 2020-01-15 19:32
Here is what I'm running:
```
##   Release = Raspbian GNU/Linux 10 (buster)
##    Kernel = Linux 4.19.75-v7l+
##  Platform = Raspberry Pi 4 Model B Rev 1.1
openHAB 2.5.0-1 (Release Build)
```

**Comment by bbogdanmircea** [comment] 2020-01-15 22:02
I could install InfluxDB manually but then influx command wouldn't work.
Then I tried some scripts I found on internet to also install influx and I crashed everything.
Then I reflashed my sdcard with openHAB and it doesn't do the self updates anymore when I connect to it with SSH.
I give up until there is some stable fix as I don't have any experience with Linux and everything seems so complicated.

**Comment by astueb** [comment] 2020-02-29 18:01
Has there been anything changed since then?
I have installed openhab and ran into the problem, too... 

no updates?

**Comment by Roadster** [comment] 2020-03-10 16:21
same for me: fresh "openHABian, ..hassle-free openHAB setup" 
https://github.com/openhab/openhabian/releases/tag/v1.5
 (( openhabian-pi-raspbian-201908050414-gitca0976f-crc6a66b5a1.img.xz ))

thx in advance
der mischa

**Comment by eikowagenknecht** [comment] 2020-04-01 11:34
I have a problem installing Influx and Grafana on openhabian as well. This is on a Raspberry Pi 3 Model B. Install outputs:

```
2020-04-01_12:46:17_CEST [openHABian] Loading configuration file '/etc/openhabian.conf'... OK
2020-04-01_12:46:17_CEST [openHABian] openHABian configuration tool version: [master]v1.5-552(869c2ea)
2020-04-01_12:46:17_CEST [openHABian] Checking for changes in origin... OK
2020-04-01_12:47:37_CEST [openHABian] Setting up InfluxDB and Grafana...

Installing InfluxDB...
--2020-04-01 12:52:45--  https://repos.influxdata.com/influxdb.key
Resolving repos.influxdata.com (repos.influxdata.com)... 2600:9000:2156:e000:7:7790:e740:93a1, 2600:9000:2156:6600:7:7790:e740:93a1, 2600:9000:2156:6e00:7:7790:
e740:93a1, ...
Connecting to repos.influxdata.com (repos.influxdata.com)|2600:9000:2156:e000:7:7790:e740:93a1|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3108 (3.0K) [application/pgp-keys]
Saving to: ‘STDOUT’

-                                       100%[===============================================================================>]   3.04K  --.-KB/s    in 0s

2020-04-01 12:52:46 (55.3 MB/s) - written to stdout [3108/3108]

OK

$ apt-get update
Hit:1 http://archive.raspberrypi.org/debian buster InRelease
Hit:2 http://raspbian.raspberrypi.org/raspbian buster InRelease
Hit:3 https://deb.nodesource.com/node_10.x buster InRelease
Ign:4 https://dl.bintray.com/openhab/apt-repo2 stable InRelease
Get:5 https://repos.influxdata.com/debian buster InRelease [4,731 B]
Get:6 https://dl.bintray.com/openhab/apt-repo2 stable Release [6,051 B]
Get:7 https://repos.influxdata.com/debian buster/stable armhf Packages [928 B]
Fetched 11.7 kB in 3s (3,483 B/s)
Reading package lists... Done

$ apt-get -y install influxdb
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  influxdb
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 59.4 MB of archives.
After this operation, 158 MB of additional disk space will be used.
Get:1 https://repos.influxdata.com/debian buster/stable armhf influxdb armhf 1.7.10-1 [59.4 MB]
Fetched 59.4 MB in 9s (6,452 kB/s)
Selecting previously unselected package influxdb.
(Reading database ... 52453 files and directories currently installed.)
Preparing to unpack .../influxdb_1.7.10-1_armhf.deb ...
Unpacking influxdb (1.7.10-1) ...
Setting up influxdb (1.7.10-1) ...
Created symlink /etc/systemd/system/influxd.service → /lib/systemd/system/influxdb.service.
Created symlink /etc/systemd/system/multi-user.target.wants/influxdb.service → /lib/systemd/system/influxdb.service.
Processing triggers for man-db (2.8.5-2) ...
Updating FireMotD available updates count ...

$ systemctl daemon-reload

$ systemctl enable influxdb.service

$ systemctl restart influxdb.service
OK Configure InfluxDB admin account... curl: (7) Failed to connect to localhost port 8086: Connection refused
FAILED Configure listen on localhost only...
$ sed -i -e /# Determines whether HTTP endpoint is enabled./ { n ; s/# enabled = true/enabled = true/ } /etc/influxdb/influxdb.conf

$ sed -i s/# bind-address = ":8086"/bind-address = "localhost:8086"/g /etc/influxdb/influxdb.conf

$ sed -i s/# auth-enabled = false/auth-enabled = true/g /etc/influxdb/influxdb.conf

$ sed -i s/# store-enabled = true/store-enabled = false/g /etc/influxdb/influxdb.conf

$ systemctl restart influxdb.service
FAILED
Setup of inital influxdb database and InfluxDB users... curl: (7) Failed to connect to localhost port 8086: Connection refused
curl: (7) Failed to connect to localhost port 8086: Connection refused
curl: (7) Failed to connect to localhost port 8086: Connection refused
curl: (7) Failed to connect to localhost port 8086: Connection refused
curl: (7) Failed to connect to localhost port 8086: Connection refused
FAILED Installing Grafana...--2020-04-01 12:54:47--  https://packages.grafana.com/gpg.key
Resolving packages.grafana.com (packages.grafana.com)... 2a04:4e42:1b::729, 151.101.114.217
Connecting to packages.grafana.com (packages.grafana.com)|2a04:4e42:1b::729|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1694 (1.7K) [application/x-iwork-keynote-sffkey]
Saving to: ‘STDOUT’

-                                       100%[===============================================================================>]   1.65K  --.-KB/s    in 0s

2020-04-01 12:54:47 (25.2 MB/s) - written to stdout [1694/1694]

OK

$ apt-get update
Hit:1 http://archive.raspberrypi.org/debian buster InRelease
Hit:2 http://raspbian.raspberrypi.org/raspbian buster InRelease
Ign:3 https://dl.bintray.com/openhab/apt-repo2 stable InRelease
Get:4 https://dl.bintray.com/openhab/apt-repo2 stable Release [6,051 B]
Hit:5 https://repos.influxdata.com/debian buster InRelease
Hit:6 https://deb.nodesource.com/node_10.x buster InRelease
Get:7 https://packages.grafana.com/oss/deb stable InRelease [12.1 kB]
Get:9 https://packages.grafana.com/oss/deb stable/main armhf Packages [15.0 kB]
Fetched 33.2 kB in 3s (10.3 kB/s)
Reading package lists... Done

$ apt-get -y install grafana
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  grafana
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 35.6 MB of archives.
After this operation, 105 MB of additional disk space will be used.
Get:1 https://packages.grafana.com/oss/deb stable/main armhf grafana armhf 6.7.1 [35.6 MB]
Fetched 35.6 MB in 9s (4,051 kB/s)
Selecting previously unselected package grafana.
(Reading database ... 52479 files and directories currently installed.)
Preparing to unpack .../grafana_6.7.1_armhf.deb ...
Unpacking grafana (6.7.1) ...
Setting up grafana (6.7.1) ...
Adding system user `grafana' (UID 111) ...
Adding new user `grafana' (UID 111) with group `grafana' ...
Not creating home directory `/usr/share/grafana'.
### NOT starting on installation, please execute the following statements to configure grafana to start automatically using systemd
 sudo /bin/systemctl daemon-reload
 sudo /bin/systemctl enable grafana-server
### You can start grafana-server by executing
 sudo /bin/systemctl start grafana-server
Processing triggers for systemd (241-7~deb10u3+rpi1) ...
Updating FireMotD available updates count ...

$ systemctl daemon-reload

$ systemctl enable grafana-server.service
Synchronizing state of grafana-server.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable grafana-server
Created symlink /etc/systemd/system/multi-user.target.wants/grafana-server.service → /usr/lib/systemd/system/grafana-server.service.

$ systemctl start grafana-server.service
OK
Updating Grafana admin password...{"message":"User password updated"}OK Updating Grafana configuration...
$ sed -i -e /^# disable user signup \/ registration/ { n ; s/^;allow_sign_up = true/allow_sign_up = false/ } /etc/grafana/grafana.ini

$ sed -i -e /^# enable anonymous access/ { n ; s/^;enabled = false/enabled = true/ } /etc/grafana/grafana.ini

$ systemctl restart grafana-server.service
Connection Grafana to InfluxDB...{"datasource":{"id":1,"orgId":1,"name":"openhab_home","type":"influxdb","typeLogoUrl":"","access":"proxy","url":"http://localho
st:8086","password":"**********","user":"grafana","database":"openhab_db","basicAuth":true,"basicAuthUser":"grafana","basicAuthPassword":"**********","withCre
dentials":false,"isDefault":false,"jsonData":{},"secureJsonFields":{},"version":1,"readOnly":false},"id":1,"message":"Datasource added","name":"openhab_home"}Ad
ding openHAB dashboard tile for Grafana... 2020-04-01_12:56:25_CEST [openHABian] Adding an openHAB dashboard tile for 'grafana'... OK
Adding install InfluxDB with database configuration to openHAB
$ touch /etc/openhab2/services/influxdb.cfg












                                                  ┌──────────────────┤ Operation Failed! ├───────────────────┐
                                                  │                                                          │
                                                  │ Sadly there was a problem setting up the selected        │
                                                  │ option. Please report this problem in the openHAB        │
                                                  │ community forum or as a openHABian GitHub issue.         │
                                                  │                                                          │
                                                  │                                                          │
                                                  │                          <Ok>                            │
                                                  │                                                          │
                                                  └──────────────────────────────────────────────────────────┘











```

**Comment by eikowagenknecht** [comment] 2020-04-01 12:08
According to the "FAILED" Messages, some commands were not executed correctly (problably DB wasn up then, maybe increase the 30s wait?). I ran these commands manually and it seems to have fixed the install:

```
curl --insecure http://localhost:8086/query --data-urlencode "q=CREATE USER admin WITH PASSWORD '**********' WITH ALL PRIVILEGES"
sudo systemctl restart influxdb.service
curl --user "admin:**********" --insecure http://localhost:8086/query --data-urlencode "q=CREATE DATABASE openhab_db"
curl --user "admin:**********" --insecure http://localhost:8086/query --data-urlencode "q=CREATE USER openhab WITH PASSWORD '**********'"
curl --user "admin:**********" --insecure http://localhost:8086/query --data-urlencode "q=CREATE USER grafana WITH PASSWORD '**********'"
curl --user "admin:**********" --insecure http://localhost:8086/query --data-urlencode "q=GRANT ALL ON openhab_db TO openhab"
curl --user "admin:**********" --insecure http://localhost:8086/query --data-urlencode "q=GRANT READ ON openhab_db TO grafana"
```

Replace with the relevant passwords of course..

**Comment by holgerfriedrich** [comment] 2020-05-03 17:54
With PR #860 merged, the influx and grafana setup changed.
Thanks, @AndyHowell, for the suggestion to reset the passwords. This is now done for Grafana and local InfluxDB installations.

I am now closing the issue, please feel free to reopen in case you still experience problems.

**Closed by holgerfriedrich** 2020-05-03 17:54 UTC
Labels: bug, optional component
