### ISSUE TITLE
Java installations fails (fix does not work)

### ISSUE THREAD

**Issue by danpadure** [openhab/openhabian#740] opened 2019-10-16 19:01 UTC
2019-10-16_21:36:44_EEST [openHABian] Adding slightly tuned vim config file to system... OK
2019-10-16_21:36:46_EEST [openHABian] Downloading and setting up FireMotD... OK
2019-10-16_21:38:56_EEST [openHABian] Installing Java Zulu 32-Bit OpenJDK...
gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
FAILED
2019-10-16_21:39:00_EEST [openHABian] Initial setup exiting with an error!

I tried the fix https://github.com/openhab/openhabian/issues/710

but it won't work
I see multiple users with the same problem here:
https://community.openhab.org/t/openhabian-config-error-on-upgrade-system/81400/2

**Comment by danjhall** [comment] 2019-10-16 19:52
I'm also having the issue, fresh install of openhabian-pi-raspbian-201908050414-gitca0976f-crc6a66b5a1.img. Tried the setup twice so far and both time it fails.

2019-10-16_20:42:27_BST [openHABian] Starting the openHABian initial setup.
2019-10-16_20:42:27_BST [openHABian] Storing configuration... OK
2019-10-16_20:42:27_BST [openHABian] Starting webserver with installation log...                                      OK
2019-10-16_20:42:32_BST [openHABian] Changing default username and password... S                                     KIPPED
2019-10-16_20:42:32_BST [openHABian] Setting up Ethernet connection... OK
2019-10-16_20:42:32_BST [openHABian] Ensuring network connectivity... OK
2019-10-16_20:42:32_BST [openHABian] Waiting for dpkg/apt to get ready... OK
2019-10-16_20:43:04_BST [openHABian] Updating repositories and upgrading install                                     ed packages... OK
2019-10-16_20:43:24_BST [openHABian] Installing git package... OK
2019-10-16_20:43:39_BST [openHABian] Cloning myself... OK
2019-10-16_20:43:42_BST [openHABian] Executing 'openhabian-setup.sh unattended'.                                     ..
2019-10-16_20:43:42_BST [openHABian] Checking for root privileges... OK
Hit:1 http://raspbian.raspberrypi.org/raspbian buster InRelease
Hit:2 http://archive.raspberrypi.org/debian buster InRelease
Reading package lists...
2019-10-16_20:43:53_BST [openHABian] Loading configuration file '/etc/openhabian                                     .conf'... OK
2019-10-16_20:43:53_BST [openHABian] Setting timezone based on IP geolocation...                                      OK (Europe/London)
2019-10-16_20:44:05_BST [openHABian] Setting locale based on openhabian.conf...                                      OK
2019-10-16_20:46:28_BST [openHABian] Setting hostname of the base system... OK
2019-10-16_20:46:28_BST [openHABian] Setting the GPU memory split down to 16MB f                                     or headless system... OK
2019-10-16_20:46:28_BST [openHABian] Enabling Audio output... OK
2019-10-16_20:46:29_BST [openHABian] Installing basic can't-be-wrong packages (s                                     creen, vim, ...)... OK
2019-10-16_20:46:37_BST [openHABian] Installing additional needed packages... OK
2019-10-16_20:46:41_BST [openHABian] Installing additional bluetooth packages...                                      OK
2019-10-16_20:46:45_BST [openHABian] Adding slightly tuned bash config files to                                      system... OK
2019-10-16_20:46:45_BST [openHABian] Adding slightly tuned vim config file to sy                                     stem... OK
2019-10-16_20:46:45_BST [openHABian] Downloading and setting up FireMotD... OK
2019-10-16_20:48:57_BST [openHABian] Installing Java Zulu 32-Bit OpenJDK...
gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
FAILED
2019-10-16_20:49:01_BST [openHABian] Initial setup exiting with an error!

**Comment by EliasGabrielsson** [comment] 2019-10-16 20:00
Duplicate of: https://github.com/openhab/openhabian/issues/734

**Closed by EliasGabrielsson** 2019-10-16 20:00 UTC
