### ISSUE TITLE
java_install_or_update runs full update even if version is already installed

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhabian#813] opened 2020-03-25 23:47 UTC
```
$ java_install_or_update
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (Zulu8.40.0.178-CA-linux_aarch32hf) (build 1.8.0_222-b178)
OpenJDK Client VM (Zulu8.40.0.178-CA-linux_aarch32hf) (build 25.222-b178, mixed mode, Evaluation)
```

**Comment by mstormi** [comment] 2020-03-26 08:56
Duplicate of #723 
This happens on every selection of 03 option Upgrade.

I was waiting for Elias to fix his Java install routine he had most recently coded but as I said no feedback for many weeks so if you dare to tackle this please do.

**Closed by mstormi** 2020-03-26 08:56 UTC
