### ISSUE TITLE
Optional Component: OLA

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhabian#98] opened 2017-02-17 13:09 UTC
Reported by "skatun": https://community.openhab.org/t/install-ola-from-git-because-apt-get-does-not-work/21140/1

The exact commands and needed checks and error conditions still need to be figured out.
Also it would be the better choice to clone the ola repository to `/opt/ola`, then link it to bin. Check openhabian itself for the steps.

```bash
sudo apt-get --assume-yes install bison
sudo apt-get --assume-yes install flex
sudo apt-get --assume-yes install uuid
sudo apt-get --assume-yes install uuid-dev
sudo apt-get --assume-yes install cppunit
sudo apt-get --assume-yes install protobuf-compiler 
sudo apt-get --assume-yes install python-protobuf
sudo apt-get --assume-yes install libprotobuf-dev 
sudo apt-get --assume-yes install libprotoc-dev
sudo apt-get --assume-yes install protobuf-compiler
sudo apt-get --assume-yes install libcppunit-dev
sudo apt-get --assume-yes install libcppunit-1.13-0
sudo apt-get --assume-yes install pkg-config
sudo apt-get --assume-yes install libncurses5-dev
sudo apt-get --assume-yes install libtool
sudo apt-get --assume-yes install libmicrohttpd-dev
sudo apt-get --assume-yes install python-numpy
sudo apt-get --assume-yes install libmicrohttpd10
sudo apt-get --assume-yes install libavahi-client-dev
sudo apt-get --assume-yes install zlib1g-dev
sudo apt-get --assume-yes install libftdi-dev
sudo apt-get --assume-yes install libftdi1 
sudo apt-get --assume-yes install libusb-1.0-0-dev
sudo apt-get --assume-yes install autoconf 
sudo apt-get --assume-yes install g++
sudo apt-get --assume-yes install make

#Already installled
#sudo apt-get --assume-yes install automake 
#sudo apt-get --assume-yes install libprotobuf-lite8 (Works without)
#sudo apt-get --assume-yes install liblo-dev(Works without)


#run this tool
sudo libtoolize

#Grab OLA

cd /bin
sudo git clone https://github.com/OpenLightingProject/ola.git
cd /bin/ola
#Install it
sudo git pull #just if you wait to continue
sudo autoreconf -i
sudo ./configure --enable-rdm-tests
sudo make
sudo make check
sudo make install
sudo ldconfig

#start OLA
#olad -l 3
```

**Comment by peternewman** [comment] 2018-11-07 14:47
We also have a package in Debian/Ubuntu/Raspbian (sudo apt-get install ola) if you don't need bleeding edge.

**Comment by peternewman** [comment] 2018-11-07 14:49
Duplicate of https://github.com/openhab/openhabian/issues/22 ?

**Comment by mstormi** [comment] 2020-03-26 22:37
Would we want to install the ola package per default ? I think no as we do not provide any config.
Please close if you agree.

**Comment by mstormi** [comment] 2020-04-17 07:22
No feedback and no apparent need. You can reopen if there's substantial news.

**Closed by mstormi** 2020-04-17 07:22 UTC
Labels: optional component

**Comment by peternewman** [comment] 2020-04-17 12:26
Sorry @mstormi I'm not sure I realised if you were targeting me. I'd suggest it but I'm biased. It should be easy enough to add retrospectively too.
