### ISSUE TITLE
Auto upgrade caused z-wave issues

### ISSUE THREAD

**Issue by jpierick** [openhab/openhabian#493] opened 2018-12-26 18:16 UTC
First I'd like to thank the developers and contributors for their great work.  This is a great way to easily get OpenHAB up and running on a RPi.  Second, I'm not sure if this is the correct place to post this so please accept my apologies in advance if it's not.  Now for the issue.  Yesterday, my RPi automatically upgraded OpenHAB from 2.3.0-1 to 2.4.0-1 (according to /var/log/apt/history.log.  OpenHAB was restarted automatically as part of that upgrade.  In the /var/log/openhab2/openhab.log file as OpenHAB was restarted after the upgrade, I saw messages like the following:  "2018-12-25 13:53:46.916 [ERROR] [ding.zwave.handler.ZWaveThingHandler] - NodeID is not set in zwave:device:1673e4146f0:node10".  At that point, none of my Z-Wave devices worked.  I just manually reverted back to OpenHAB 2.3.0-1 and everything is working fine again.

**Comment by EliasGabrielsson** [comment] 2018-12-28 23:59
Hi @jpierick.
It's a shame that your system broke, sound like an auto update where performed of the packages somehow. (Regular system maintenance `apt-get upgrade`)

Regarding your issue have you read the post about breakning changes for zwave?
https://community.openhab.org/t/zwave-binding-updates/51080 It sound like that was the cause of for the issue. 

Closing this now as it's not directly related to openhabian. Please reopen if you thinks otherwise!

**Closed by EliasGabrielsson** 2018-12-28 23:59 UTC
