### ISSUE TITLE
Node-Red installation via openhabian-config don't work

### ISSUE THREAD

**Issue by blachner** [openhab/openhabian#738] opened 2019-10-11 19:58 UTC
Node-Red installation via openhabian-config don't work. It seems installation is completed but it don't go back to openhabian-config (maybe because of missing file /usr/bin/update-nodejs-and-nodered)  and Node-Red isn't started after this.

This is the output from the second try on a Raspberry Pi 3:

Running Node-RED install for user openhabian at /home/openhabian on raspbian\n

This can take 20-30 minutes on the slower Pi versions - please wait.

  Stop Node-RED                       ✔
  Remove old version of Node-RED      ✔
  Remove old version of Node.js       -
  Leave existing Node.js              -   Node v10.16.3   Npm 6.12.0
  Clean npm cache                     -
  Install Node-RED core               ✔   1.0.1 
  Move global nodes to local          -
  Install extra Pi nodes              ✔
  Npm rebuild existing nodes          -
  Add shortcut commands               ✔
  Update systemd script               ✔
                                           

Any errors will be logged to   /var/log/nodered-install.log

All done.
  You can now start Node-RED with the command  node-red-start
  or using the icon under   Menu / Programming / Node-RED
  Then point your browser to localhost:1880 or http://{your_pi_ip-address}:1880

Started  Fr 11. Okt 21:37:52 CEST 2019  -  Finished  Fr 11. Okt 21:39:40 CEST 2019

rm: das Entfernen von '/usr/bin/update-nodejs-and-nodered' ist nicht möglich: Datei oder Verzeichnis nicht gefunden
FAILED (nodered)

**Comment by mstormi** [comment] 2019-10-12 08:21
related ?
https://community.openhab.org/t/solved-node-red-not-visible/83407

**Comment by blachner** [comment] 2019-10-12 11:45
I don't know if this is related. It seems, in my case, Node Red base installation is finished. I can start it with systemctrl. I don't know, if openhabian-config normally does more installation steps instead printing "FAILED (nodered)"? At least I think, normally  openhabian-config enables Node Red to start on system start ans insert an entry to the openhab dashboard, like it does with grafana?

**Comment by r00li** [comment] 2019-10-12 18:43
I've just tried to install Node Red on my Raspberry Pi running Openhabian and I can confirm this issue. The exact same thing happens here. The installation fails with No such file or directory error. Node red can be started using the command line and works otherwise. But it does not start after reboot and it is not added to the dashboard.

**Comment by c0d35io** [comment] 2019-10-13 15:35
I could also confirm this on a Raspberry Pi 4, also the open hab specific nodes are not installed/integrated in Node Red, i guess something is crashing here during installation routine and post-setup steps are maybe not triggered 🤷🏼‍♂️

**Comment by CNC-Maniac** [comment] 2019-10-29 07:50
> related ?
> https://community.openhab.org/t/solved-node-red-not-visible/83407

Yes it seems to be the same. Is there anything new here? I'm not very good with linux ..

**Comment by c0d35io** [comment] 2019-11-01 19:49
You can use the quickfix, which i posted. 

Since the problem wont be fixed by node red (see node-red/raspbian-deb-package#13) the error handling in the openhabian installer for node red needs to be adapted

**Comment by CNC-Maniac** [comment] 2019-12-04 10:43
> You can use the quickfix, which i posted.
> 
> Since the problem wont be fixed by node red (see [node-red/raspbian-deb-package#13](https://github.com/node-red/raspbian-deb-package/pull/13)) the error handling in the openhabian installer for node red needs to be adapted

I tried, but I can not find the file. Possibly. a permission is missing. That's really bad. I think that's it, as long as it's not possible to create simple things like a weekday clock, with Paper-UI, there's no way around Node-Red. It is all the more important that it is reinstalled without detours.

**Comment by bummzulu** [comment] 2020-01-04 09:37
I was also missing the openhab related nodes after the installation of node red. I added them by installing the nodes right from the node red GUI (manage palette).

**Comment by eikowagenknecht** [comment] 2020-03-24 13:36
This fix also worked for me and is a bit simpler to execute than the solution from @c0d35io:

1. sudo touch /usr/bin/update-nodejs-and-nodered
2. sudo openhabian-config
3. Instal Node-Red from there as usual

The manually created file is removed by the install script and it is happy ;-)

Should still be fixed in openhabian config tool.

**Closed** 2020-03-26 09:39 UTC
